# To go to GitPod, go to https://gitpod.io/#https://github.com/PowerNukkit/PowerNukkit/

tasks:
  - before: bash mvnw clean install
    init: cd target
    command: java -jar powernukkit-*-shaded.jar
ports:
  - port: 19132
