package cn.nukkit.item;

import cn.nukkit.utils.material.ItemType;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.objects.Object2ObjectMap;
import it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap;
import lombok.Data;


public class ItemTypes {

    private static final Int2ObjectMap<ItemType> types = new Int2ObjectOpenHashMap<>();
    private static final Object2ObjectMap<String, ItemType> identifiers = new Object2ObjectOpenHashMap<>();

    public static final ItemType IRON_SHOVEL = register("minecraft:iron_shovel", ItemID.IRON_SHOVEL);
    public static final ItemType IRON_PICKAXE = register("minecraft:iron_pickaxe", ItemID.IRON_PICKAXE);
    public static final ItemType IRON_AXE = register("minecraft:iron_axe", ItemID.IRON_AXE);
    public static final ItemType FLINT_STEEL = register("minecraft:flint_and_steel", ItemID.FLINT_STEEL);
    public static final ItemType FLINT_AND_STEEL = register("minecraft:flint_and_steel", ItemID.FLINT_AND_STEEL);
    public static final ItemType APPLE = register("minecraft:apple", ItemID.APPLE);
    public static final ItemType BOW = register("minecraft:bow", ItemID.BOW);
    public static final ItemType ARROW = register("minecraft:arrow", ItemID.ARROW);
    public static final ItemType COAL = register("minecraft:coal", ItemID.COAL);
    public static final ItemType DIAMOND = register("minecraft:diamond", ItemID.DIAMOND);
    public static final ItemType IRON_INGOT = register("minecraft:iron_ingot", ItemID.IRON_INGOT);
    public static final ItemType GOLD_INGOT = register("minecraft:gold_ingot", ItemID.GOLD_INGOT);
    public static final ItemType IRON_SWORD = register("minecraft:iron_sword", ItemID.IRON_SWORD);
    public static final ItemType WOODEN_SWORD = register("minecraft:wooden_sword", ItemID.WOODEN_SWORD);
    public static final ItemType WOODEN_SHOVEL = register("minecraft:wooden_shovel", ItemID.WOODEN_SHOVEL);
    public static final ItemType WOODEN_PICKAXE = register("minecraft:wooden_pickaxe", ItemID.WOODEN_PICKAXE);
    public static final ItemType WOODEN_AXE = register("minecraft:wooden_axe", ItemID.WOODEN_AXE);
    public static final ItemType STONE_SWORD = register("minecraft:stone_sword", ItemID.STONE_SWORD);
    public static final ItemType STONE_SHOVEL = register("minecraft:stone_shovel", ItemID.STONE_SHOVEL);
    public static final ItemType STONE_PICKAXE = register("minecraft:stone_pickaxe", ItemID.STONE_PICKAXE);
    public static final ItemType STONE_AXE = register("minecraft:stone_axe", ItemID.STONE_AXE);
    public static final ItemType DIAMOND_SWORD = register("minecraft:diamond_sword", ItemID.DIAMOND_SWORD);
    public static final ItemType DIAMOND_SHOVEL = register("minecraft:diamond_shovel", ItemID.DIAMOND_SHOVEL);
    public static final ItemType DIAMOND_PICKAXE = register("minecraft:diamond_pickaxe", ItemID.DIAMOND_PICKAXE);
    public static final ItemType DIAMOND_AXE = register("minecraft:diamond_axe", ItemID.DIAMOND_AXE);
    public static final ItemType STICK = register("minecraft:stick", ItemID.STICK);
    public static final ItemType STICKS = register("minecraft:stick", ItemID.STICKS);
    public static final ItemType BOWL = register("minecraft:bowl", ItemID.BOWL);
    public static final ItemType MUSHROOM_STEW = register("minecraft:mushroom_stew", ItemID.MUSHROOM_STEW);
    public static final ItemType GOLD_SWORD = register("minecraft:golden_sword", ItemID.GOLD_SWORD);
    public static final ItemType GOLDEN_SWORD = register("minecraft:golden_sword", ItemID.GOLDEN_SWORD);
    public static final ItemType GOLD_SHOVEL = register("minecraft:golden_shovel", ItemID.GOLD_SHOVEL);
    public static final ItemType GOLDEN_SHOVEL = register("minecraft:golden_shovel", ItemID.GOLDEN_SHOVEL);
    public static final ItemType GOLD_PICKAXE = register("minecraft:golden_pickaxe", ItemID.GOLD_PICKAXE);
    public static final ItemType GOLDEN_PICKAXE = register("minecraft:golden_pickaxe", ItemID.GOLDEN_PICKAXE);
    public static final ItemType GOLD_AXE = register("minecraft:golden_axe", ItemID.GOLD_AXE);
    public static final ItemType GOLDEN_AXE = register("minecraft:golden_axe", ItemID.GOLDEN_AXE);
    public static final ItemType STRING = register("minecraft:string", ItemID.STRING);
    public static final ItemType FEATHER = register("minecraft:feather", ItemID.FEATHER);
    public static final ItemType GUNPOWDER = register("minecraft:gunpowder", ItemID.GUNPOWDER);
    public static final ItemType WOODEN_HOE = register("minecraft:wooden_hoe", ItemID.WOODEN_HOE);
    public static final ItemType STONE_HOE = register("minecraft:stone_hoe", ItemID.STONE_HOE);
    public static final ItemType IRON_HOE = register("minecraft:iron_hoe", ItemID.IRON_HOE);
    public static final ItemType DIAMOND_HOE = register("minecraft:diamond_hoe", ItemID.DIAMOND_HOE);
    public static final ItemType GOLD_HOE = register("minecraft:golden_hoe", ItemID.GOLD_HOE);
    public static final ItemType GOLDEN_HOE = register("minecraft:golden_hoe", ItemID.GOLDEN_HOE);
    public static final ItemType SEEDS = register("minecraft:wheat_seeds", ItemID.SEEDS);
    public static final ItemType WHEAT_SEEDS = register("minecraft:wheat_seeds", ItemID.WHEAT_SEEDS);
    public static final ItemType WHEAT = register("minecraft:wheat", ItemID.WHEAT);
    public static final ItemType BREAD = register("minecraft:bread", ItemID.BREAD);
    public static final ItemType LEATHER_CAP = register("minecraft:leather_helmet", ItemID.LEATHER_CAP);
    public static final ItemType LEATHER_HELMET = register("minecraft:leather_helmet", ItemID.LEATHER_HELMET);
    public static final ItemType LEATHER_TUNIC = register("minecraft:leather_chestplate", ItemID.LEATHER_TUNIC);
    public static final ItemType LEATHER_CHESTPLATE = register("minecraft:leather_chestplate", ItemID.LEATHER_CHESTPLATE);
    public static final ItemType LEATHER_PANTS = register("minecraft:leather_leggings", ItemID.LEATHER_PANTS);
    public static final ItemType LEATHER_LEGGINGS = register("minecraft:leather_leggings", ItemID.LEATHER_LEGGINGS);
    public static final ItemType LEATHER_BOOTS = register("minecraft:leather_boots", ItemID.LEATHER_BOOTS);
    public static final ItemType CHAIN_HELMET = register("minecraft:chainmail_helmet", ItemID.CHAIN_HELMET);
    public static final ItemType CHAINMAIL_HELMET = register("minecraft:chainmail_helmet", ItemID.CHAINMAIL_HELMET);
    public static final ItemType CHAIN_CHESTPLATE = register("minecraft:chainmail_chestplate", ItemID.CHAIN_CHESTPLATE);
    public static final ItemType CHAINMAIL_CHESTPLATE = register("minecraft:chainmail_chestplate", ItemID.CHAINMAIL_CHESTPLATE);
    public static final ItemType CHAIN_LEGGINGS = register("minecraft:chainmail_leggings", ItemID.CHAIN_LEGGINGS);
    public static final ItemType CHAINMAIL_LEGGINGS = register("minecraft:chainmail_leggings", ItemID.CHAINMAIL_LEGGINGS);
    public static final ItemType CHAIN_BOOTS = register("minecraft:chainmail_boots", ItemID.CHAIN_BOOTS);
    public static final ItemType CHAINMAIL_BOOTS = register("minecraft:chainmail_boots", ItemID.CHAINMAIL_BOOTS);
    public static final ItemType IRON_HELMET = register("minecraft:iron_helmet", ItemID.IRON_HELMET);
    public static final ItemType IRON_CHESTPLATE = register("minecraft:iron_chestplate", ItemID.IRON_CHESTPLATE);
    public static final ItemType IRON_LEGGINGS = register("minecraft:iron_leggings", ItemID.IRON_LEGGINGS);
    public static final ItemType IRON_BOOTS = register("minecraft:iron_boots", ItemID.IRON_BOOTS);
    public static final ItemType DIAMOND_HELMET = register("minecraft:diamond_helmet", ItemID.DIAMOND_HELMET);
    public static final ItemType DIAMOND_CHESTPLATE = register("minecraft:diamond_chestplate", ItemID.DIAMOND_CHESTPLATE);
    public static final ItemType DIAMOND_LEGGINGS = register("minecraft:diamond_leggings", ItemID.DIAMOND_LEGGINGS);
    public static final ItemType DIAMOND_BOOTS = register("minecraft:diamond_boots", ItemID.DIAMOND_BOOTS);
    public static final ItemType GOLD_HELMET = register("minecraft:golden_helmet", ItemID.GOLD_HELMET);
    public static final ItemType GOLDEN_HELMET = register("minecraft:golden_helmet", ItemID.GOLDEN_HELMET);
    public static final ItemType GOLD_CHESTPLATE = register("minecraft:golden_chestplate", ItemID.GOLD_CHESTPLATE);
    public static final ItemType GOLDEN_CHESTPLATE = register("minecraft:golden_chestplate", ItemID.GOLDEN_CHESTPLATE);
    public static final ItemType GOLD_LEGGINGS = register("minecraft:golden_leggings", ItemID.GOLD_LEGGINGS);
    public static final ItemType GOLDEN_LEGGINGS = register("minecraft:golden_leggings", ItemID.GOLDEN_LEGGINGS);
    public static final ItemType GOLD_BOOTS = register("minecraft:golden_boots", ItemID.GOLD_BOOTS);
    public static final ItemType GOLDEN_BOOTS = register("minecraft:golden_boots", ItemID.GOLDEN_BOOTS);
    public static final ItemType FLINT = register("minecraft:flint", ItemID.FLINT);
    public static final ItemType RAW_PORKCHOP = register("minecraft:porkchop", ItemID.RAW_PORKCHOP);
    public static final ItemType COOKED_PORKCHOP = register("minecraft:cooked_porkchop", ItemID.COOKED_PORKCHOP);
    public static final ItemType PAINTING = register("minecraft:painting", ItemID.PAINTING);
    public static final ItemType GOLDEN_APPLE = register("minecraft:golden_apple", ItemID.GOLDEN_APPLE);
    public static final ItemType SIGN = register("minecraft:oak_sign", ItemID.SIGN);
    public static final ItemType WOODEN_DOOR = register("minecraft:wooden_door", ItemID.WOODEN_DOOR);
    public static final ItemType BUCKET = register("minecraft:bucket", ItemID.BUCKET);
    public static final ItemType MINECART = register("minecraft:minecart", ItemID.MINECART);
    public static final ItemType SADDLE = register("minecraft:saddle", ItemID.SADDLE);
    public static final ItemType IRON_DOOR = register("minecraft:iron_door", ItemID.IRON_DOOR);
    public static final ItemType REDSTONE = register("minecraft:redstone", ItemID.REDSTONE);
    public static final ItemType REDSTONE_DUST = register("minecraft:redstone", ItemID.REDSTONE_DUST);
    public static final ItemType SNOWBALL = register("minecraft:snowball", ItemID.SNOWBALL);
    public static final ItemType BOAT = register("minecraft:boat", ItemID.BOAT);
    public static final ItemType LEATHER = register("minecraft:leather", ItemID.LEATHER);
    public static final ItemType KELP = register("minecraft:kelp", ItemID.KELP);
    public static final ItemType BRICK = register("minecraft:brick", ItemID.BRICK);
    public static final ItemType CLAY = register("minecraft:clay_ball", ItemID.CLAY);
    public static final ItemType CLAY_BALL = register("minecraft:clay_ball", ItemID.CLAY_BALL);
    public static final ItemType SUGARCANE = register("minecraft:sugar_cane", ItemID.SUGARCANE);
    public static final ItemType SUGAR_CANE = register("minecraft:sugar_cane", ItemID.SUGAR_CANE);
    public static final ItemType SUGAR_CANES = register("minecraft:sugar_cane", ItemID.SUGAR_CANES);
    public static final ItemType PAPER = register("minecraft:paper", ItemID.PAPER);
    public static final ItemType BOOK = register("minecraft:book", ItemID.BOOK);
    public static final ItemType SLIMEBALL = register("minecraft:slime_ball", ItemID.SLIMEBALL);
    public static final ItemType SLIME_BALL = register("minecraft:slime_ball", ItemID.SLIME_BALL);
    public static final ItemType CHEST_MINECART = register("minecraft:chest_minecart", ItemID.CHEST_MINECART);
    public static final ItemType MINECART_WITH_CHEST = register("minecraft:chest_minecart", ItemID.MINECART_WITH_CHEST);
    public static final ItemType EGG = register("minecraft:egg", ItemID.EGG);
    public static final ItemType COMPASS = register("minecraft:compass", ItemID.COMPASS);
    public static final ItemType FISHING_ROD = register("minecraft:fishing_rod", ItemID.FISHING_ROD);
    public static final ItemType CLOCK = register("minecraft:clock", ItemID.CLOCK);
    public static final ItemType GLOWSTONE_DUST = register("minecraft:glowstone_dust", ItemID.GLOWSTONE_DUST);
    public static final ItemType RAW_FISH = register("minecraft:cod", ItemID.RAW_FISH);
    public static final ItemType COOKED_FISH = register("minecraft:cooked_cod", ItemID.COOKED_FISH);
    public static final ItemType DYE = register("minecraft:dye", ItemID.DYE);
    public static final ItemType BONE = register("minecraft:bone", ItemID.BONE);
    public static final ItemType SUGAR = register("minecraft:sugar", ItemID.SUGAR);
    public static final ItemType CAKE = register("minecraft:cake", ItemID.CAKE);
    public static final ItemType BED = register("minecraft:bed", ItemID.BED);
    public static final ItemType REPEATER = register("minecraft:repeater", ItemID.REPEATER);
    public static final ItemType COOKIE = register("minecraft:cookie", ItemID.COOKIE);
    public static final ItemType MAP = register("minecraft:filled_map", ItemID.MAP);
    public static final ItemType SHEARS = register("minecraft:shears", ItemID.SHEARS);
    public static final ItemType MELON = register("minecraft:melon_slice", ItemID.MELON);
    public static final ItemType MELON_SLICE = register("minecraft:melon_slice", ItemID.MELON_SLICE);
    public static final ItemType PUMPKIN_SEEDS = register("minecraft:pumpkin_seeds", ItemID.PUMPKIN_SEEDS);
    public static final ItemType MELON_SEEDS = register("minecraft:melon_seeds", ItemID.MELON_SEEDS);
    public static final ItemType BEEF = register("minecraft:beef", ItemID.BEEF);
    public static final ItemType RAW_BEEF = register("minecraft:beef", ItemID.RAW_BEEF);
    public static final ItemType STEAK = register("minecraft:cooked_beef", ItemID.STEAK);
    public static final ItemType COOKED_BEEF = register("minecraft:cooked_beef", ItemID.COOKED_BEEF);
    public static final ItemType RAW_CHICKEN = register("minecraft:chicken", ItemID.RAW_CHICKEN);
    public static final ItemType CHICKEN = register("minecraft:chicken", ItemID.CHICKEN);
    public static final ItemType COOKED_CHICKEN = register("minecraft:cooked_chicken", ItemID.COOKED_CHICKEN);
    public static final ItemType ROTTEN_FLESH = register("minecraft:rotten_flesh", ItemID.ROTTEN_FLESH);
    public static final ItemType ENDER_PEARL = register("minecraft:ender_pearl", ItemID.ENDER_PEARL);
    public static final ItemType BLAZE_ROD = register("minecraft:blaze_rod", ItemID.BLAZE_ROD);
    public static final ItemType GHAST_TEAR = register("minecraft:ghast_tear", ItemID.GHAST_TEAR);
    public static final ItemType GOLD_NUGGET = register("minecraft:gold_nugget", ItemID.GOLD_NUGGET);
    public static final ItemType GOLDEN_NUGGET = register("minecraft:gold_nugget", ItemID.GOLDEN_NUGGET);
    public static final ItemType NETHER_WART = register("minecraft:nether_wart", ItemID.NETHER_WART);
    public static final ItemType POTION = register("minecraft:potion", ItemID.POTION);
    public static final ItemType GLASS_BOTTLE = register("minecraft:glass_bottle", ItemID.GLASS_BOTTLE);
    public static final ItemType BOTTLE = register("minecraft:glass_bottle", ItemID.BOTTLE);
    public static final ItemType SPIDER_EYE = register("minecraft:spider_eye", ItemID.SPIDER_EYE);
    public static final ItemType FERMENTED_SPIDER_EYE = register("minecraft:fermented_spider_eye", ItemID.FERMENTED_SPIDER_EYE);
    public static final ItemType BLAZE_POWDER = register("minecraft:blaze_powder", ItemID.BLAZE_POWDER);
    public static final ItemType MAGMA_CREAM = register("minecraft:magma_cream", ItemID.MAGMA_CREAM);
    public static final ItemType BREWING_STAND = register("minecraft:brewing_stand", ItemID.BREWING_STAND);
    public static final ItemType BREWING = register("minecraft:brewing_stand", ItemID.BREWING);
    public static final ItemType CAULDRON = register("minecraft:cauldron", ItemID.CAULDRON);
    public static final ItemType ENDER_EYE = register("minecraft:ender_eye", ItemID.ENDER_EYE);
    public static final ItemType GLISTERING_MELON = register("minecraft:glistering_melon_slice", ItemID.GLISTERING_MELON);
    public static final ItemType GLISTERING_MELON_SLICE = register("minecraft:glistering_melon_slice", ItemID.GLISTERING_MELON_SLICE);
    public static final ItemType SPAWN_EGG = register("minecraft:spawn_egg", ItemID.SPAWN_EGG);
    public static final ItemType EXPERIENCE_BOTTLE = register("minecraft:experience_bottle", ItemID.EXPERIENCE_BOTTLE);
    public static final ItemType FIRE_CHARGE = register("minecraft:fire_charge", ItemID.FIRE_CHARGE);
    public static final ItemType BOOK_AND_QUILL = register("minecraft:writable_book", ItemID.BOOK_AND_QUILL);
    public static final ItemType WRITTEN_BOOK = register("minecraft:written_book", ItemID.WRITTEN_BOOK);
    public static final ItemType EMERALD = register("minecraft:emerald", ItemID.EMERALD);
    public static final ItemType ITEM_FRAME = register("minecraft:frame", ItemID.ITEM_FRAME);
    public static final ItemType FRAME = register("minecraft:frame", ItemID.FRAME);
    public static final ItemType FLOWER_POT = register("minecraft:flower_pot", ItemID.FLOWER_POT);
    public static final ItemType CARROT = register("minecraft:carrot", ItemID.CARROT);
    public static final ItemType CARROTS = register("minecraft:carrot", ItemID.CARROTS);
    public static final ItemType POTATO = register("minecraft:potato", ItemID.POTATO);
    public static final ItemType POTATOES = register("minecraft:potato", ItemID.POTATOES);
    public static final ItemType BAKED_POTATO = register("minecraft:baked_potato", ItemID.BAKED_POTATO);
    public static final ItemType BAKED_POTATOES = register("minecraft:baked_potato", ItemID.BAKED_POTATOES);
    public static final ItemType POISONOUS_POTATO = register("minecraft:poisonous_potato", ItemID.POISONOUS_POTATO);
    public static final ItemType EMPTY_MAP = register("minecraft:empty_map", ItemID.EMPTY_MAP);
    public static final ItemType EMPTYMAP = register("minecraft:empty_map", ItemID.EMPTYMAP);
    public static final ItemType GOLDEN_CARROT = register("minecraft:golden_carrot", ItemID.GOLDEN_CARROT);
    public static final ItemType SKULL = register("minecraft:skull", ItemID.SKULL);
    public static final ItemType CARROTONASTICK = register("minecraft:carrot_on_a_stick", ItemID.CARROTONASTICK);
    public static final ItemType CARROT_ON_A_STICK = register("minecraft:carrot_on_a_stick", ItemID.CARROT_ON_A_STICK);
    public static final ItemType NETHER_STAR = register("minecraft:nether_star", ItemID.NETHER_STAR);
    public static final ItemType PUMPKIN_PIE = register("minecraft:pumpkin_pie", ItemID.PUMPKIN_PIE);
    public static final ItemType FIREWORKS = register("minecraft:firework_rocket", ItemID.FIREWORKS);
    public static final ItemType FIREWORKSCHARGE = register("minecraft:firework_star", ItemID.FIREWORKSCHARGE);
    public static final ItemType ENCHANTED_BOOK = register("minecraft:enchanted_book", ItemID.ENCHANTED_BOOK);
    public static final ItemType ENCHANT_BOOK = register("minecraft:enchanted_book", ItemID.ENCHANT_BOOK);
    public static final ItemType COMPARATOR = register("minecraft:comparator", ItemID.COMPARATOR);
    public static final ItemType NETHER_BRICK = register("minecraft:netherbrick", ItemID.NETHER_BRICK);
    public static final ItemType QUARTZ = register("minecraft:quartz", ItemID.QUARTZ);
    public static final ItemType NETHER_QUARTZ = register("minecraft:quartz", ItemID.NETHER_QUARTZ);
    public static final ItemType TNT_MINECART = register("minecraft:tnt_minecart", ItemID.TNT_MINECART);
    public static final ItemType MINECART_WITH_TNT = register("minecraft:tnt_minecart", ItemID.MINECART_WITH_TNT);
    public static final ItemType HOPPER_MINECART = register("minecraft:hopper_minecart", ItemID.HOPPER_MINECART);
    public static final ItemType MINECART_WITH_HOPPER = register("minecraft:hopper_minecart", ItemID.MINECART_WITH_HOPPER);
    public static final ItemType PRISMARINE_SHARD = register("minecraft:prismarine_shard", ItemID.PRISMARINE_SHARD);
    public static final ItemType HOPPER = register("minecraft:hopper", ItemID.HOPPER);
    public static final ItemType RAW_RABBIT = register("minecraft:rabbit", ItemID.RAW_RABBIT);
    public static final ItemType RABBIT = register("minecraft:rabbit", ItemID.RABBIT);
    public static final ItemType COOKED_RABBIT = register("minecraft:cooked_rabbit", ItemID.COOKED_RABBIT);
    public static final ItemType RABBIT_STEW = register("minecraft:rabbit_stew", ItemID.RABBIT_STEW);
    public static final ItemType RABBIT_FOOT = register("minecraft:rabbit_foot", ItemID.RABBIT_FOOT);
    public static final ItemType RABBIT_HIDE = register("minecraft:rabbit_hide", ItemID.RABBIT_HIDE);
    public static final ItemType LEATHER_HORSE_ARMOR = register("minecraft:leather_horse_armor", ItemID.LEATHER_HORSE_ARMOR);
    public static final ItemType IRON_HORSE_ARMOR = register("minecraft:iron_horse_armor", ItemID.IRON_HORSE_ARMOR);
    public static final ItemType GOLD_HORSE_ARMOR = register("minecraft:golden_horse_armor", ItemID.GOLD_HORSE_ARMOR);
    public static final ItemType GOLDEN_HORSE_ARMOR = register("minecraft:golden_horse_armor", ItemID.GOLDEN_HORSE_ARMOR);
    public static final ItemType DIAMOND_HORSE_ARMOR = register("minecraft:diamond_horse_armor", ItemID.DIAMOND_HORSE_ARMOR);
    public static final ItemType LEAD = register("minecraft:lead", ItemID.LEAD);
    public static final ItemType NAME_TAG = register("minecraft:name_tag", ItemID.NAME_TAG);
    public static final ItemType NAMETAG = register("minecraft:name_tag", ItemID.NAMETAG);
    public static final ItemType PRISMARINE_CRYSTALS = register("minecraft:prismarine_crystals", ItemID.PRISMARINE_CRYSTALS);
    public static final ItemType RAW_MUTTON = register("minecraft:mutton", ItemID.RAW_MUTTON);
    public static final ItemType MUTTONRAW = register("minecraft:mutton", ItemID.MUTTONRAW);
    public static final ItemType COOKED_MUTTON = register("minecraft:cooked_mutton", ItemID.COOKED_MUTTON);
    public static final ItemType ARMOR_STAND = register("minecraft:armor_stand", ItemID.ARMOR_STAND);
    public static final ItemType END_CRYSTAL = register("minecraft:end_crystal", ItemID.END_CRYSTAL);
    public static final ItemType SPRUCE_DOOR = register("minecraft:spruce_door", ItemID.SPRUCE_DOOR);
    public static final ItemType BIRCH_DOOR = register("minecraft:birch_door", ItemID.BIRCH_DOOR);
    public static final ItemType JUNGLE_DOOR = register("minecraft:jungle_door", ItemID.JUNGLE_DOOR);
    public static final ItemType ACACIA_DOOR = register("minecraft:acacia_door", ItemID.ACACIA_DOOR);
    public static final ItemType DARK_OAK_DOOR = register("minecraft:dark_oak_door", ItemID.DARK_OAK_DOOR);
    public static final ItemType CHORUS_FRUIT = register("minecraft:chorus_fruit", ItemID.CHORUS_FRUIT);
    public static final ItemType POPPED_CHORUS_FRUIT = register("minecraft:popped_chorus_fruit", ItemID.POPPED_CHORUS_FRUIT);
    public static final ItemType BANNER_PATTERN = register("minecraft:banner_pattern", ItemID.BANNER_PATTERN);
    public static final ItemType DRAGON_BREATH = register("minecraft:dragon_breath", ItemID.DRAGON_BREATH);
    public static final ItemType SPLASH_POTION = register("minecraft:splash_potion", ItemID.SPLASH_POTION);
    public static final ItemType LINGERING_POTION = register("minecraft:lingering_potion", ItemID.LINGERING_POTION);
    public static final ItemType SPARKLER = register("minecraft:sparkler", ItemID.SPARKLER);
    public static final ItemType COMMAND_BLOCK_MINECART = register("minecraft:command_block_minecart", ItemID.COMMAND_BLOCK_MINECART);
    public static final ItemType ELYTRA = register("minecraft:elytra", ItemID.ELYTRA);
    public static final ItemType SHULKER_SHELL = register("minecraft:shulker_shell", ItemID.SHULKER_SHELL);
    public static final ItemType BANNER = register("minecraft:banner", ItemID.BANNER);
    public static final ItemType EYE_DROP = register("minecraft:medicine", ItemID.EYE_DROP);
    public static final ItemType BALLOON = register("minecraft:balloon", ItemID.BALLOON);
    public static final ItemType SUPER_FERTILIZER = register("minecraft:rapid_fertilizer", ItemID.SUPER_FERTILIZER);
    public static final ItemType TOTEM = register("minecraft:totem_of_undying", ItemID.TOTEM);
    public static final ItemType BLEACH = register("minecraft:bleach", ItemID.BLEACH);
    public static final ItemType IRON_NUGGET = register("minecraft:iron_nugget", ItemID.IRON_NUGGET);
    public static final ItemType ICE_BOMB = register("minecraft:ice_bomb", ItemID.ICE_BOMB);
    public static final ItemType TRIDENT = register("minecraft:trident", ItemID.TRIDENT);
    public static final ItemType BEETROOT = register("minecraft:beetroot", ItemID.BEETROOT);
    public static final ItemType BEETROOT_SEEDS = register("minecraft:beetroot_seeds", ItemID.BEETROOT_SEEDS);
    public static final ItemType BEETROOT_SEED = register("minecraft:beetroot_seeds", ItemID.BEETROOT_SEED);
    public static final ItemType BEETROOT_SOUP = register("minecraft:beetroot_soup", ItemID.BEETROOT_SOUP);
    public static final ItemType RAW_SALMON = register("minecraft:salmon", ItemID.RAW_SALMON);
    public static final ItemType CLOWNFISH = register("minecraft:tropical_fish", ItemID.CLOWNFISH);
    public static final ItemType PUFFERFISH = register("minecraft:pufferfish", ItemID.PUFFERFISH);
    public static final ItemType COOKED_SALMON = register("minecraft:cooked_salmon", ItemID.COOKED_SALMON);
    public static final ItemType DRIED_KELP = register("minecraft:dried_kelp", ItemID.DRIED_KELP);
    public static final ItemType NAUTILUS_SHELL = register("minecraft:nautilus_shell", ItemID.NAUTILUS_SHELL);
    public static final ItemType GOLDEN_APPLE_ENCHANTED = register("minecraft:enchanted_golden_apple", ItemID.GOLDEN_APPLE_ENCHANTED);
    public static final ItemType ENCHANTED_GOLDEN_APPLE = register("minecraft:enchanted_golden_apple", ItemID.ENCHANTED_GOLDEN_APPLE);
    public static final ItemType APPLEENCHANTED = register("minecraft:enchanted_golden_apple", ItemID.APPLEENCHANTED);
    public static final ItemType HEART_OF_THE_SEA = register("minecraft:heart_of_the_sea", ItemID.HEART_OF_THE_SEA);
    public static final ItemType SCUTE = register("minecraft:turtle_scute", ItemID.SCUTE);
    public static final ItemType TURTLE_SCUTE = register("minecraft:turtle_scute", ItemID.TURTLE_SCUTE);
    public static final ItemType TURTLE_SHELL = register("minecraft:turtle_helmet", ItemID.TURTLE_SHELL);
    public static final ItemType TURTLE_HELMET = register("minecraft:turtle_helmet", ItemID.TURTLE_HELMET);
    public static final ItemType PHANTOM_MEMBRANE = register("minecraft:phantom_membrane", ItemID.PHANTOM_MEMBRANE);
    public static final ItemType CROSSBOW = register("minecraft:crossbow", ItemID.CROSSBOW);
    public static final ItemType SPRUCE_SIGN = register("minecraft:spruce_sign", ItemID.SPRUCE_SIGN);
    public static final ItemType BIRCH_SIGN = register("minecraft:birch_sign", ItemID.BIRCH_SIGN);
    public static final ItemType JUNGLE_SIGN = register("minecraft:jungle_sign", ItemID.JUNGLE_SIGN);
    public static final ItemType ACACIA_SIGN = register("minecraft:acacia_sign", ItemID.ACACIA_SIGN);
    public static final ItemType DARKOAK_SIGN = register("minecraft:dark_oak_sign", ItemID.DARKOAK_SIGN);
    public static final ItemType SWEET_BERRIES = register("minecraft:sweet_berries", ItemID.SWEET_BERRIES);
    public static final ItemType CAMERA = register("minecraft:camera", ItemID.CAMERA);
    public static final ItemType COMPOUND = register("minecraft:compound", ItemID.COMPOUND);
    public static final ItemType RECORD_13 = register("minecraft:music_disc_13", ItemID.RECORD_13);
    public static final ItemType RECORD_CAT = register("minecraft:music_disc_cat", ItemID.RECORD_CAT);
    public static final ItemType RECORD_BLOCKS = register("minecraft:music_disc_blocks", ItemID.RECORD_BLOCKS);
    public static final ItemType RECORD_CHIRP = register("minecraft:music_disc_chirp", ItemID.RECORD_CHIRP);
    public static final ItemType RECORD_FAR = register("minecraft:music_disc_far", ItemID.RECORD_FAR);
    public static final ItemType RECORD_MALL = register("minecraft:music_disc_mall", ItemID.RECORD_MALL);
    public static final ItemType RECORD_MELLOHI = register("minecraft:music_disc_mellohi", ItemID.RECORD_MELLOHI);
    public static final ItemType RECORD_STAL = register("minecraft:music_disc_stal", ItemID.RECORD_STAL);
    public static final ItemType RECORD_STRAD = register("minecraft:music_disc_strad", ItemID.RECORD_STRAD);
    public static final ItemType RECORD_WARD = register("minecraft:music_disc_ward", ItemID.RECORD_WARD);
    public static final ItemType RECORD_11 = register("minecraft:music_disc_11", ItemID.RECORD_11);
    public static final ItemType RECORD_WAIT = register("minecraft:music_disc_wait", ItemID.RECORD_WAIT);
    public static final ItemType SHIELD = register("minecraft:shield", ItemID.SHIELD);
    public static final ItemType COPPER_INGOT = register("minecraft:copper_ingot", ItemID.COPPER_INGOT);
    public static final ItemType RAW_IRON = register("minecraft:raw_iron", ItemID.RAW_IRON);
    public static final ItemType RAW_GOLD = register("minecraft:raw_gold", ItemID.RAW_GOLD);
    public static final ItemType RAW_COPPER = register("minecraft:raw_copper", ItemID.RAW_COPPER);
    public static final ItemType RECORD_5 = register("minecraft:music_disc_5", ItemID.RECORD_5);
    public static final ItemType DISC_FRAGMENT_5 = register("minecraft:disc_fragment_5", ItemID.DISC_FRAGMENT_5);
    public static final ItemType OAK_CHEST_BOAT = register("minecraft:oak_chest_boat", ItemID.OAK_CHEST_BOAT);
    public static final ItemType BIRCH_CHEST_BOAT = register("minecraft:birch_chest_boat", ItemID.BIRCH_CHEST_BOAT);
    public static final ItemType JUNGLE_CHEST_BOAT = register("minecraft:jungle_chest_boat", ItemID.JUNGLE_CHEST_BOAT);
    public static final ItemType SPRUCE_CHEST_BOAT = register("minecraft:spruce_chest_boat", ItemID.SPRUCE_CHEST_BOAT);
    public static final ItemType ACACIA_CHEST_BOAT = register("minecraft:acacia_chest_boat", ItemID.ACACIA_CHEST_BOAT);
    public static final ItemType DARK_OAK_CHEST_BOAT = register("minecraft:dark_oak_chest_boat", ItemID.DARK_OAK_CHEST_BOAT);
    public static final ItemType MANGROVE_CHEST_BOAT = register("minecraft:mangrove_chest_boat", ItemID.MANGROVE_CHEST_BOAT);
    public static final ItemType ECHO_SHARD = register("minecraft:echo_shard", ItemID.ECHO_SHARD);
    public static final ItemType RECOVERY_COMPASS = register("minecraft:recovery_compass", ItemID.RECOVERY_COMPASS);
    public static final ItemType GLOW_BERRIES = register("minecraft:glow_berries", ItemID.GLOW_BERRIES);
    public static final ItemType RECORD_RELIC = register("minecraft:music_disc_relic", ItemID.RECORD_RELIC);
    public static final ItemType CAMPFIRE = register("minecraft:campfire", ItemID.CAMPFIRE);
    public static final ItemType SUSPICIOUS_STEW = register("minecraft:suspicious_stew", ItemID.SUSPICIOUS_STEW);
    public static final ItemType HONEYCOMB = register("minecraft:honeycomb", ItemID.HONEYCOMB);
    public static final ItemType HONEY_BOTTLE = register("minecraft:honey_bottle", ItemID.HONEY_BOTTLE);
    public static final ItemType LODESTONECOMPASS = register("minecraft:lodestone_compass", ItemID.LODESTONECOMPASS);
    public static final ItemType LODESTONE_COMPASS = register("minecraft:lodestone_compass", ItemID.LODESTONE_COMPASS);
    public static final ItemType NETHERITE_INGOT = register("minecraft:netherite_ingot", ItemID.NETHERITE_INGOT);
    public static final ItemType NETHERITE_SWORD = register("minecraft:netherite_sword", ItemID.NETHERITE_SWORD);
    public static final ItemType NETHERITE_SHOVEL = register("minecraft:netherite_shovel", ItemID.NETHERITE_SHOVEL);
    public static final ItemType NETHERITE_PICKAXE = register("minecraft:netherite_pickaxe", ItemID.NETHERITE_PICKAXE);
    public static final ItemType NETHERITE_AXE = register("minecraft:netherite_axe", ItemID.NETHERITE_AXE);
    public static final ItemType NETHERITE_HOE = register("minecraft:netherite_hoe", ItemID.NETHERITE_HOE);
    public static final ItemType NETHERITE_HELMET = register("minecraft:netherite_helmet", ItemID.NETHERITE_HELMET);
    public static final ItemType NETHERITE_CHESTPLATE = register("minecraft:netherite_chestplate", ItemID.NETHERITE_CHESTPLATE);
    public static final ItemType NETHERITE_LEGGINGS = register("minecraft:netherite_leggings", ItemID.NETHERITE_LEGGINGS);
    public static final ItemType NETHERITE_BOOTS = register("minecraft:netherite_boots", ItemID.NETHERITE_BOOTS);
    public static final ItemType NETHERITE_SCRAP = register("minecraft:netherite_scrap", ItemID.NETHERITE_SCRAP);
    public static final ItemType CRIMSON_SIGN = register("minecraft:crimson_sign", ItemID.CRIMSON_SIGN);
    public static final ItemType WARPED_SIGN = register("minecraft:warped_sign", ItemID.WARPED_SIGN);
    public static final ItemType CRIMSON_DOOR = register("minecraft:crimson_door", ItemID.CRIMSON_DOOR);
    public static final ItemType WARPED_DOOR = register("minecraft:warped_door", ItemID.WARPED_DOOR);
    public static final ItemType WARPED_FUNGUS_ON_A_STICK = register("minecraft:warped_fungus_on_a_stick", ItemID.WARPED_FUNGUS_ON_A_STICK);
    public static final ItemType CHAIN = register("minecraft:chain", ItemID.CHAIN);
    public static final ItemType RECORD_PIGSTEP = register("minecraft:music_disc_pigstep", ItemID.RECORD_PIGSTEP);
    public static final ItemType NETHER_SPROUTS = register("minecraft:nether_sprouts", ItemID.NETHER_SPROUTS);
    public static final ItemType GOAT_HORN = register("minecraft:goat_horn", ItemID.GOAT_HORN);
    public static final ItemType AMETHYST_SHARD = register("minecraft:amethyst_shard", ItemID.AMETHYST_SHARD);
    public static final ItemType SPYGLASS = register("minecraft:spyglass", ItemID.SPYGLASS);
    public static final ItemType RECORD_OTHERSIDE = register("minecraft:music_disc_otherside", ItemID.RECORD_OTHERSIDE);
    public static final ItemType SOUL_CAMPFIRE = register("minecraft:soul_campfire", ItemID.SOUL_CAMPFIRE);
    public static final ItemType GLOW_ITEM_FRAME = register("minecraft:glow_frame", ItemID.GLOW_ITEM_FRAME);

    private static ItemType register(String identifier, int legacyId) {
        return register(new ItemTypeImpl(identifier, legacyId));
    }

    private static ItemType register(ItemType itemType) {
        ItemType old = types.putIfAbsent(itemType.getLegacyId(), itemType);
        /*if (old != null) { // TODO: there are alternate names for some items
            throw new IllegalArgumentException("Item type with id " + itemType.getLegacyId() + " already exists: " + old);
        }*/
        identifiers.putIfAbsent(itemType.getIdentifier(), itemType); // TODO: using identifiers.put() would be better
        return old == null ? itemType : old;
    }

    public static ItemType getFromLegacy(int legacyId) {
        return types.get(legacyId);
    }

    public static ItemType get(String identifier) {
        return identifiers.get(identifier);
    }

    @Data
    private static class ItemTypeImpl implements ItemType {
        private final String identifier;
        private final int legacyId;
    }
}
