package cn.nukkit.network.protocol;

import cn.nukkit.Nukkit;
import cn.nukkit.Server;
import cn.nukkit.math.Vector3f;
import cn.nukkit.utils.BinaryStream;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import lombok.ToString;

@ToString
public class LevelSoundEventPacket extends DataPacket {

    public static final byte NETWORK_ID = ProtocolInfo.LEVEL_SOUND_EVENT_PACKET;

    public static final int SOUND_ITEM_USE_ON = 0;
    public static final int SOUND_HIT = 1;
    public static final int SOUND_STEP = 2;
    public static final int SOUND_FLY = 3;
    public static final int SOUND_JUMP = 4;
    public static final int SOUND_BREAK = 5;
    public static final int SOUND_PLACE = 6;
    public static final int SOUND_HEAVY_STEP = 7;
    public static final int SOUND_GALLOP = 8;
    public static final int SOUND_FALL = 9;
    public static final int SOUND_AMBIENT = 10;
    public static final int SOUND_AMBIENT_BABY = 11;
    public static final int SOUND_AMBIENT_IN_WATER = 12;
    public static final int SOUND_BREATHE = 13;
    public static final int SOUND_DEATH = 14;
    public static final int SOUND_DEATH_IN_WATER = 15;
    public static final int SOUND_DEATH_TO_ZOMBIE = 16;
    public static final int SOUND_HURT = 17;
    public static final int SOUND_HURT_IN_WATER = 18;
    public static final int SOUND_MAD = 19;
    public static final int SOUND_BOOST = 20;
    public static final int SOUND_BOW = 21;
    public static final int SOUND_SQUISH_BIG = 22;
    public static final int SOUND_SQUISH_SMALL = 23;
    public static final int SOUND_FALL_BIG = 24;
    public static final int SOUND_FALL_SMALL = 25;
    public static final int SOUND_SPLASH = 26;
    public static final int SOUND_FIZZ = 27;
    public static final int SOUND_FLAP = 28;
    public static final int SOUND_SWIM = 29;
    public static final int SOUND_DRINK = 30;
    public static final int SOUND_EAT = 31;
    public static final int SOUND_TAKEOFF = 32;
    public static final int SOUND_SHAKE = 33;
    public static final int SOUND_PLOP = 34;
    public static final int SOUND_LAND = 35;
    public static final int SOUND_SADDLE = 36;
    public static final int SOUND_ARMOR = 37;
    public static final int SOUND_MOB_ARMOR_STAND_PLACE = 38;
    public static final int SOUND_ADD_CHEST = 39;
    public static final int SOUND_THROW = 40;
    public static final int SOUND_ATTACK = 41;
    public static final int SOUND_ATTACK_NODAMAGE = 42;
    public static final int SOUND_ATTACK_STRONG = 43;
    public static final int SOUND_WARN = 44;
    public static final int SOUND_SHEAR = 45;
    public static final int SOUND_MILK = 46;
    public static final int SOUND_THUNDER = 47;
    public static final int SOUND_EXPLODE = 48;
    public static final int SOUND_FIRE = 49;
    public static final int SOUND_IGNITE = 50;
    public static final int SOUND_FUSE = 51;
    public static final int SOUND_STARE = 52;
    public static final int SOUND_SPAWN = 53;
    public static final int SOUND_SHOOT = 54;
    public static final int SOUND_BREAK_BLOCK = 55;
    public static final int SOUND_LAUNCH = 56;
    public static final int SOUND_BLAST = 57;
    public static final int SOUND_LARGE_BLAST = 58;
    public static final int SOUND_TWINKLE = 59;
    public static final int SOUND_REMEDY = 60;
    public static final int SOUND_UNFECT = 61;
    public static final int SOUND_LEVELUP = 62;
    public static final int SOUND_BOW_HIT = 63;
    public static final int SOUND_BULLET_HIT = 64;
    public static final int SOUND_EXTINGUISH_FIRE = 65;
    public static final int SOUND_ITEM_FIZZ = 66;
    public static final int SOUND_CHEST_OPEN = 67;
    public static final int SOUND_CHEST_CLOSED = 68;
    public static final int SOUND_SHULKERBOX_OPEN = 69;
    public static final int SOUND_SHULKERBOX_CLOSED = 70;
    public static final int SOUND_ENDERCHEST_OPEN = 71;
    public static final int SOUND_ENDERCHEST_CLOSED = 72;
    public static final int SOUND_POWER_ON = 73;
    public static final int SOUND_POWER_OFF = 74;
    public static final int SOUND_ATTACH = 75;
    public static final int SOUND_DETACH = 76;
    public static final int SOUND_DENY = 77;
    public static final int SOUND_TRIPOD = 78;
    public static final int SOUND_POP = 79;
    public static final int SOUND_DROP_SLOT = 80;
    public static final int SOUND_NOTE = 81;
    public static final int SOUND_THORNS = 82;
    public static final int SOUND_PISTON_IN = 83;
    public static final int SOUND_PISTON_OUT = 84;
    public static final int SOUND_PORTAL = 85;
    public static final int SOUND_WATER = 86;
    public static final int SOUND_LAVA_POP = 87;
    public static final int SOUND_LAVA = 88;
    public static final int SOUND_BURP = 89;
    public static final int SOUND_BUCKET_FILL_WATER = 90;
    public static final int SOUND_BUCKET_FILL_LAVA = 91;
    public static final int SOUND_BUCKET_EMPTY_WATER = 92;
    public static final int SOUND_BUCKET_EMPTY_LAVA = 93;
    public static final int SOUND_ARMOR_EQUIP_CHAIN = 94;
    public static final int SOUND_ARMOR_EQUIP_DIAMOND = 95;
    public static final int SOUND_ARMOR_EQUIP_GENERIC = 96;
    public static final int SOUND_ARMOR_EQUIP_GOLD = 97;
    public static final int SOUND_ARMOR_EQUIP_IRON = 98;
    public static final int SOUND_ARMOR_EQUIP_LEATHER = 99;
    public static final int SOUND_ARMOR_EQUIP_ELYTRA = 100;
    public static final int SOUND_RECORD_13 = 101;
    public static final int SOUND_RECORD_CAT = 102;
    public static final int SOUND_RECORD_BLOCKS = 103;
    public static final int SOUND_RECORD_CHIRP = 104;
    public static final int SOUND_RECORD_FAR = 105;
    public static final int SOUND_RECORD_MALL = 106;
    public static final int SOUND_RECORD_MELLOHI = 107;
    public static final int SOUND_RECORD_STAL = 108;
    public static final int SOUND_RECORD_STRAD = 109;
    public static final int SOUND_RECORD_WARD = 110;
    public static final int SOUND_RECORD_11 = 111;
    public static final int SOUND_RECORD_WAIT = 112;
    public static final int SOUND_STOP_RECORD = 113;
    public static final int SOUND_GUARDIAN_FLOP = 114;
    public static final int SOUND_ELDERGUARDIAN_CURSE = 115;
    public static final int SOUND_MOB_WARNING = 116;
    public static final int SOUND_MOB_WARNING_BABY = 117;
    public static final int SOUND_TELEPORT = 118;
    public static final int SOUND_SHULKER_OPEN = 119;
    public static final int SOUND_SHULKER_CLOSE = 120;
    public static final int SOUND_HAGGLE = 121;
    public static final int SOUND_HAGGLE_YES = 122;
    public static final int SOUND_HAGGLE_NO = 123;
    public static final int SOUND_HAGGLE_IDLE = 124;
    public static final int SOUND_CHORUSGROW = 125;
    public static final int SOUND_CHORUSDEATH = 126;
    public static final int SOUND_GLASS = 127;
    public static final int SOUND_POTION_BREWED = 128;
    public static final int SOUND_CAST_SPELL = 129;
    public static final int SOUND_PREPARE_ATTACK = 130;
    public static final int SOUND_PREPARE_SUMMON = 131;
    public static final int SOUND_PREPARE_WOLOLO = 132;
    public static final int SOUND_FANG = 133;
    public static final int SOUND_CHARGE = 134;
    public static final int SOUND_CAMERA_TAKE_PICTURE = 135;
    public static final int SOUND_LEASHKNOT_PLACE = 136;
    public static final int SOUND_LEASHKNOT_BREAK = 137;
    public static final int SOUND_GROWL = 138;
    public static final int SOUND_WHINE = 139;
    public static final int SOUND_PANT = 140;
    public static final int SOUND_PURR = 141;
    public static final int SOUND_PURREOW = 142;
    public static final int SOUND_DEATH_MIN_VOLUME = 143;
    public static final int SOUND_DEATH_MID_VOLUME = 144;
    public static final int SOUND_IMITATE_BLAZE = 145;
    public static final int SOUND_IMITATE_CAVE_SPIDER = 146;
    public static final int SOUND_IMITATE_CREEPER = 147;
    public static final int SOUND_IMITATE_ELDER_GUARDIAN = 148;
    public static final int SOUND_IMITATE_ENDER_DRAGON = 149;
    public static final int SOUND_IMITATE_ENDERMAN = 150;
    public static final int SOUND_IMITATE_ENDERMITE = 151;
    public static final int SOUND_IMITATE_EVOCATION_ILLAGER = 152;
    public static final int SOUND_IMITATE_GHAST = 153;
    public static final int SOUND_IMITATE_HUSK = 154;
    public static final int SOUND_IMITATE_ILLUSION_ILLAGER = 155;
    public static final int SOUND_IMITATE_MAGMA_CUBE = 156;
    public static final int SOUND_IMITATE_POLAR_BEAR = 157;
    public static final int SOUND_IMITATE_SHULKER = 158;
    public static final int SOUND_IMITATE_SILVERFISH = 159;
    public static final int SOUND_IMITATE_SKELETON = 160;
    public static final int SOUND_IMITATE_SLIME = 161;
    public static final int SOUND_IMITATE_SPIDER = 162;
    public static final int SOUND_IMITATE_STRAY = 163;
    public static final int SOUND_IMITATE_VEX = 164;
    public static final int SOUND_IMITATE_VINDICATION_ILLAGER = 165;
    public static final int SOUND_IMITATE_WITCH = 166;
    public static final int SOUND_IMITATE_WITHER = 167;
    public static final int SOUND_IMITATE_WITHER_SKELETON = 168;
    public static final int SOUND_IMITATE_WOLF = 169;
    public static final int SOUND_IMITATE_ZOMBIE = 170;
    public static final int SOUND_IMITATE_ZOMBIE_PIGMAN = 171;
    public static final int SOUND_IMITATE_ZOMBIE_VILLAGER = 172;
    public static final int SOUND_BLOCK_END_PORTAL_FRAME_FILL = 173;
    public static final int SOUND_BLOCK_END_PORTAL_SPAWN = 174;
    public static final int SOUND_RANDOM_ANVIL_USE = 175;
    public static final int SOUND_BOTTLE_DRAGONBREATH = 176;
    public static final int SOUND_PORTAL_TRAVEL = 177;
    public static final int SOUND_ITEM_TRIDENT_HIT = 178;
    public static final int SOUND_ITEM_TRIDENT_RETURN = 179;
    public static final int SOUND_ITEM_TRIDENT_RIPTIDE_1 = 180;
    public static final int SOUND_ITEM_TRIDENT_RIPTIDE_2 = 181;
    public static final int SOUND_ITEM_TRIDENT_RIPTIDE_3 = 182;
    public static final int SOUND_ITEM_TRIDENT_THROW = 183;
    public static final int SOUND_ITEM_TRIDENT_THUNDER = 184;
    public static final int SOUND_ITEM_TRIDENT_HIT_GROUND = 185;
    public static final int SOUND_DEFAULT = 186;
    public static final int SOUND_BLOCK_FLETCHING_TABLE_USE = 187;
    public static final int SOUND_ELEMCONSTRUCT_OPEN = 188;
    public static final int SOUND_ICEBOMB_HIT = 189;
    public static final int SOUND_BALLOONPOP = 190;
    public static final int SOUND_LT_REACTION_ICEBOMB = 191;
    public static final int SOUND_LT_REACTION_BLEACH = 192;
    public static final int SOUND_LT_REACTION_EPASTE = 193;
    public static final int SOUND_LT_REACTION_EPASTE2 = 194;
    public static final int SOUND_LT_REACTION_GLOW_STICK = 195;
    public static final int SOUND_LT_REACTION_GLOW_STICK_2 = 196;
    public static final int SOUND_LT_REACTION_LUMINOL = 197;
    public static final int SOUND_LT_REACTION_SALT = 198;
    public static final int SOUND_LT_REACTION_FERTILIZER = 199;
    public static final int SOUND_LT_REACTION_FIREBALL = 200;
    public static final int SOUND_LT_REACTION_MGSALT = 201;
    public static final int SOUND_LT_REACTION_MISCFIRE = 202;
    public static final int SOUND_LT_REACTION_FIRE = 203;
    public static final int SOUND_LT_REACTION_MISCEXPLOSION = 204;
    public static final int SOUND_LT_REACTION_MISCMYSTICAL = 205;
    public static final int SOUND_LT_REACTION_MISCMYSTICAL2 = 206;
    public static final int SOUND_LT_REACTION_PRODUCT = 207;
    public static final int SOUND_SPARKLER_USE = 208;
    public static final int SOUND_GLOWSTICK_USE = 209;
    public static final int SOUND_SPARKLER_ACTIVE = 210;
    public static final int SOUND_CONVERT_TO_DROWNED = 211;
    public static final int SOUND_BUCKET_FILL_FISH = 212;
    public static final int SOUND_BUCKET_EMPTY_FISH = 213;
    public static final int SOUND_BUBBLE_UP = 214;
    public static final int SOUND_BUBBLE_DOWN = 215;
    public static final int SOUND_BUBBLE_POP = 216;
    public static final int SOUND_BUBBLE_UPINSIDE = 217;
    public static final int SOUND_BUBBLE_DOWNINSIDE = 218;
    public static final int SOUND_HURT_BABY = 219;
    public static final int SOUND_DEATH_BABY = 220;
    public static final int SOUND_STEP_BABY = 221;
    public static final int SOUND_SPAWN_BABY = 222;
    public static final int SOUND_BORN = 223;
    public static final int SOUND_BLOCK_TURTLE_EGG_BREAK = 224;
    public static final int SOUND_BLOCK_TURTLE_EGG_CRACK = 225;
    public static final int SOUND_BLOCK_TURTLE_EGG_HATCH = 226;
    public static final int SOUND_LAY_EGG = 227;
    public static final int SOUND_BLOCK_TURTLE_EGG_ATTACK = 228;
    public static final int SOUND_BEACON_ACTIVATE = 229;
    public static final int SOUND_BEACON_AMBIENT = 230;
    public static final int SOUND_BEACON_DEACTIVATE = 231;
    public static final int SOUND_BEACON_POWER = 232;
    public static final int SOUND_CONDUIT_ACTIVATE = 233;
    public static final int SOUND_CONDUIT_AMBIENT = 234;
    public static final int SOUND_CONDUIT_ATTACK = 235;
    public static final int SOUND_CONDUIT_DEACTIVATE = 236;
    public static final int SOUND_CONDUIT_SHORT = 237;
    public static final int SOUND_SWOOP = 238;
    public static final int SOUND_BLOCK_BAMBOO_SAPLING_PLACE = 239;
    public static final int SOUND_PRESNEEZE = 240;
    public static final int SOUND_SNEEZE = 241;
    public static final int SOUND_AMBIENT_TAME = 242;
    public static final int SOUND_SCARED = 243;
    public static final int SOUND_BLOCK_SCAFFOLDING_CLIMB = 244;
    public static final int SOUND_CROSSBOW_LOADING_START = 245;
    public static final int SOUND_CROSSBOW_LOADING_MIDDLE = 246;
    public static final int SOUND_CROSSBOW_LOADING_END = 247;
    public static final int SOUND_CROSSBOW_SHOOT = 248;
    public static final int SOUND_CROSSBOW_QUICK_CHARGE_START = 249;
    public static final int SOUND_CROSSBOW_QUICK_CHARGE_MIDDLE = 250;
    public static final int SOUND_CROSSBOW_QUICK_CHARGE_END = 251;
    public static final int SOUND_AMBIENT_AGGRESSIVE = 252;
    public static final int SOUND_AMBIENT_WORRIED = 253;
    public static final int SOUND_CANT_BREED = 254;
    public static final int SOUND_ITEM_SHIELD_BLOCK = 255;
    public static final int SOUND_ITEM_BOOK_PUT = 256;
    public static final int SOUND_BLOCK_GRINDSTONE_USE = 257;
    public static final int SOUND_BLOCK_BELL_HIT = 258;
    public static final int SOUND_BLOCK_CAMPFIRE_CRACKLE = 259;
    public static final int SOUND_ROAR = 260;
    public static final int SOUND_STUN = 261;
    public static final int SOUND_BLOCK_SWEET_BERRY_BUSH_HURT = 262;
    public static final int SOUND_BLOCK_SWEET_BERRY_BUSH_PICK = 263;
    public static final int SOUND_BLOCK_CARTOGRAPHY_TABLE_USE = 264;
    public static final int SOUND_BLOCK_STONECUTTER_USE = 265;
    public static final int SOUND_BLOCK_COMPOSTER_EMPTY = 266;
    public static final int SOUND_BLOCK_COMPOSTER_FILL = 267;
    public static final int SOUND_BLOCK_COMPOSTER_FILL_SUCCESS = 268;
    public static final int SOUND_BLOCK_COMPOSTER_READY = 269;
    public static final int SOUND_BLOCK_BARREL_OPEN = 270;
    public static final int SOUND_BLOCK_BARREL_CLOSE = 271;
    public static final int SOUND_RAID_HORN = 272;
    public static final int SOUND_BLOCK_LOOM_USE = 273;
    public static final int SOUND_AMBIENT_IN_RAID = 274;
    public static final int SOUND_UI_CARTOGRAPHY_TABLE_TAKE_RESULT = 275;
    public static final int SOUND_UI_STONECUTTER_TAKE_RESULT = 276;
    public static final int SOUND_UI_LOOM_TAKE_RESULT = 277;
    public static final int SOUND_BLOCK_SMOKER_SMOKE = 278;
    public static final int SOUND_BLOCK_BLASTFURNACE_FIRE_CRACKLE = 279;
    public static final int SOUND_BLOCK_SMITHING_TABLE_USE = 280;
    public static final int SOUND_SCREECH = 281;
    public static final int SOUND_SLEEP = 282;
    public static final int SOUND_BLOCK_FURNACE_LIT = 283;
    public static final int SOUND_CONVERT_MOOSHROOM = 284;
    public static final int SOUND_MILK_SUSPICIOUSLY = 285;
    public static final int SOUND_CELEBRATE = 286;
    public static final int SOUND_JUMP_PREVENT = 287;
    public static final int SOUND_AMBIENT_POLLINATE = 288;
    public static final int SOUND_BLOCK_BEEHIVE_DRIP = 289;
    public static final int SOUND_BLOCK_BEEHIVE_ENTER = 290;
    public static final int SOUND_BLOCK_BEEHIVE_EXIT = 291;
    public static final int SOUND_BLOCK_BEEHIVE_WORK = 292;
    public static final int SOUND_BLOCK_BEEHIVE_SHEAR = 293;
    public static final int SOUND_DRINK_HONEY = 294;
    public static final int SOUND_AMBIENT_CAVE = 295;
    public static final int SOUND_RETREAT = 296;
    public static final int SOUND_CONVERTED_TO_ZOMBIFIED = 297;
    public static final int SOUND_ADMIRE = 298;
    public static final int SOUND_STEP_LAVA = 299;
    public static final int SOUND_TEMPT = 300;
    public static final int SOUND_PANIC = 301;
    public static final int SOUND_ANGRY = 302;
    public static final int SOUND_AMBIENT_WARPED_FOREST_MOOD = 303;
    public static final int SOUND_AMBIENT_SOULSAND_VALLEY_MOOD = 304;
    public static final int SOUND_AMBIENT_NETHER_WASTES_MOOD = 305;
    public static final int SOUND_RESPAWN_ANCHOR_BASALT_DELTAS_MOOD = 306;
    public static final int SOUND_AMBIENT_CRIMSON_FOREST_MOOD = 307;
    public static final int SOUND_RESPAWN_ANCHOR_CHARGE = 308;
    public static final int SOUND_RESPAWN_ANCHOR_DEPLETE = 309;
    public static final int SOUND_RESPAWN_ANCHOR_SET_SPAWN = 310;
    public static final int SOUND_RESPAWN_ANCHOR_AMBIENT = 311;
    public static final int SOUND_PARTICLE_SOUL_ESCAPE_QUIET = 312;
    public static final int SOUND_PARTICLE_SOUL_ESCAPE_LOUD = 313;
    public static final int SOUND_RECORD_PIGSTEP = 314;
    public static final int SOUND_LODESTONE_COMPASS_LINK_COMPASS_TO_LODESTONE = 315;
    public static final int SOUND_SMITHING_TABLE_USE = 316;
    public static final int SOUND_ARMOR_EQUIP_NETHERITE = 317;
    public static final int SOUND_AMBIENT_WARPED_FOREST_LOOP = 318;
    public static final int SOUND_AMBIENT_SOULSAND_VALLEY_LOOP = 319;
    public static final int SOUND_AMBIENT_NETHER_WASTES_LOOP = 320;
    public static final int SOUND_AMBIENT_BASALT_DELTAS_LOOP = 321;
    public static final int SOUND_AMBIENT_CRIMSON_FOREST_LOOP = 322;
    public static final int SOUND_AMBIENT_WARPED_FOREST_ADDITIONS = 323;
    public static final int SOUND_AMBIENT_SOULSAND_VALLEY_ADDITIONS = 324;
    public static final int SOUND_AMBIENT_NETHER_WASTES_ADDITIONS = 325;
    public static final int SOUND_AMBIENT_BASALT_DELTAS_ADDITIONS = 326;
    public static final int SOUND_AMBIENT_CRIMSON_FOREST_ADDITIONS = 327;
    public static final int SOUND_SCULK_SENSOR_POWER_ON = 328;
    public static final int SOUND_SCULK_SENSOR_POWER_OFF = 329;
    public static final int SOUND_BUCKET_FILL_POWDER_SNOW = 330;
    public static final int SOUND_BUCKET_EMPTY_POWDER_SNOW = 331;
    public static final int SOUND_POINTED_DRIPSTONE_CAULDRON_DRIP_WATER = 332;
    public static final int SOUND_POINTED_DRIPSTONE_CAULDRON_DRIP_LAVA = 333;
    public static final int SOUND_POINTED_DRIPSTONE_DRIP_WATER = 334;
    public static final int SOUND_POINTED_DRIPSTONE_DRIP_LAVA = 335;
    public static final int SOUND_CAVE_VINES_PICK_BERRIES = 336;
    public static final int SOUND_BIG_DRIPLEAF_TILT_DOWN = 337;
    public static final int SOUND_BIG_DRIPLEAF_TILT_UP = 338;
    public static final int SOUND_COPPER_WAX_ON = 339;
    public static final int SOUND_COPPER_WAX_OFF = 340;
    public static final int SOUND_SCRAPE = 341;
    public static final int SOUND_PLAYER_HURT_DROWN = 342;
    public static final int SOUND_PLAYER_HURT_ON_FIRE = 343;
    public static final int SOUND_PLAYER_HURT_FREEZE = 344;
    public static final int SOUND_USE_SPYGLASS = 345;
    public static final int SOUND_STOP_USING_SPYGLASS = 346;
    public static final int SOUND_AMETHYST_BLOCK_CHIME = 347;
    public static final int SOUND_AMBIENT_SCREAMER = 348;
    public static final int SOUND_HURT_SCREAMER = 349;
    public static final int SOUND_DEATH_SCREAMER = 350;
    public static final int SOUND_MILK_SCREAMER = 351;
    public static final int SOUND_JUMP_TO_BLOCK = 352;
    public static final int SOUND_PRE_RAM = 353;
    public static final int SOUND_PRE_RAM_SCREAMER = 354;
    public static final int SOUND_RAM_IMPACT = 355;
    public static final int SOUND_RAM_IMPACT_SCREAMER = 356;
    public static final int SOUND_SQUID_INK_SQUIRT = 357;
    public static final int SOUND_GLOW_SQUID_INK_SQUIRT = 358;
    public static final int SOUND_CONVERT_TO_STRAY = 359;
    public static final int SOUND_CAKE_ADD_CANDLE = 360;
    public static final int SOUND_EXTINGUISH_CANDLE = 361;
    public static final int SOUND_AMBIENT_CANDLE = 362;
    public static final int SOUND_BLOCK_CLICK = 363;
    public static final int SOUND_BLOCK_CLICK_FAIL = 364;
    public static final int SOUND_SCULK_CATALYST_BLOOM = 365;
    public static final int SOUND_SCULK_SHRIEKER_SHRIEK = 366;
    public static final int SOUND_WARDEN_NEARBY_CLOSE = 367;
    public static final int SOUND_WARDEN_NEARBY_CLOSER = 368;
    public static final int SOUND_WARDEN_NEARBY_CLOSEST = 369;
    public static final int SOUND_WARDEN_SLIGHTLY_ANGRY = 370;
    public static final int SOUND_RECORD_OTHERSIDE = 371;
    public static final int SOUND_TONGUE = 372;
    public static final int SOUND_CRACK_IRON_GOLEM = 373;
    public static final int SOUND_REPAIR_IRON_GOLEM = 374;
    public static final int SOUND_LISTENING = 375;
    public static final int SOUND_HEARTBEAT = 376;
    public static final int SOUND_HORN_BREAK = 377;
    public static final int SOUND_SCULK_PLACE = 378;
    public static final int SOUND_SCULK_SPREAD = 379;
    public static final int SOUND_SCULK_CHARGE = 380;
    public static final int SOUND_SCULK_SENSOR_PLACE = 381;
    public static final int SOUND_SCULK_SHRIEKER_PLACE = 382;
    public static final int SOUND_GOAT_CALL_0 = 383;
    public static final int SOUND_GOAT_CALL_1 = 384;
    public static final int SOUND_GOAT_CALL_2 = 385;
    public static final int SOUND_GOAT_CALL_3 = 386;
    public static final int SOUND_GOAT_CALL_4 = 387;
    public static final int SOUND_GOAT_CALL_5 = 388;
    public static final int SOUND_GOAT_CALL_6 = 389;
    public static final int SOUND_GOAT_CALL_7 = 390;
    public static final int SOUND_GOAT_CALL_8 = 391;
    public static final int SOUND_GOAT_CALL_9 = 392;
    public static final int SOUND_GOAT_HARMONY_0 = 393;
    public static final int SOUND_GOAT_HARMONY_1 = 394;
    public static final int SOUND_GOAT_HARMONY_2 = 395;
    public static final int SOUND_GOAT_HARMONY_3 = 396;
    public static final int SOUND_GOAT_HARMONY_4 = 397;
    public static final int SOUND_GOAT_HARMONY_5 = 398;
    public static final int SOUND_GOAT_HARMONY_6 = 399;
    public static final int SOUND_GOAT_HARMONY_7 = 400;
    public static final int SOUND_GOAT_HARMONY_8 = 401;
    public static final int SOUND_GOAT_HARMONY_9 = 402;
    public static final int SOUND_GOAT_MELODY_0 = 403;
    public static final int SOUND_GOAT_MELODY_1 = 404;
    public static final int SOUND_GOAT_MELODY_2 = 405;
    public static final int SOUND_GOAT_MELODY_3 = 406;
    public static final int SOUND_GOAT_MELODY_4 = 407;
    public static final int SOUND_GOAT_MELODY_5 = 408;
    public static final int SOUND_GOAT_MELODY_6 = 409;
    public static final int SOUND_GOAT_MELODY_7 = 410;
    public static final int SOUND_GOAT_MELODY_8 = 411;
    public static final int SOUND_GOAT_MELODY_9 = 412;
    public static final int SOUND_GOAT_BASS_0 = 413;
    public static final int SOUND_GOAT_BASS_1 = 414;
    public static final int SOUND_GOAT_BASS_2 = 415;
    public static final int SOUND_GOAT_BASS_3 = 416;
    public static final int SOUND_GOAT_BASS_4 = 417;
    public static final int SOUND_GOAT_BASS_5 = 418;
    public static final int SOUND_GOAT_BASS_6 = 419;
    public static final int SOUND_GOAT_BASS_7 = 420;
    public static final int SOUND_GOAT_BASS_8 = 421;
    public static final int SOUND_GOAT_BASS_9 = 422;
    public static final int SOUND_IMITATE_WARDEN = 426;
    public static final int SOUND_LISTENING_ANGRY = 427;
    public static final int SOUND_ITEM_GIVEN = 428;
    public static final int SOUND_ITEM_TAKEN = 429;
    public static final int SOUND_DISAPPEARED = 430;
    public static final int SOUND_REAPPEARED = 431;
    public static final int SOUND_MILK_DRINK = 432;
    public static final int SOUND_FROGSPAWN_HATCHED = 433;
    public static final int SOUND_LAY_SPAWN = 434;
    public static final int SOUND_FROGSPAWN_BREAK = 435;
    public static final int SOUND_SONIC_BOOM = 436;
    public static final int SOUND_SONIC_CHARGE = 437;
    public static final int SOUND_ITEM_THROWN = 438;
    public static final int SOUND_RECORD_5 = 439;
    public static final int SOUND_CONVERT_TO_FROG = 440;
    public static final int SOUND_RECORD_PLAYING = 441;
    public static final int SOUND_ENCHANTING_TABLE_USE = 442;
    public static final int SOUND_PRESSURE_PLATE_CLICK_OFF = 448;
    public static final int SOUND_PRESSURE_PLATE_CLICK_ON = 449;
    public static final int SOUND_BUTTON_CLICK_OFF = 450;
    public static final int SOUND_BUTTON_CLICK_ON = 451;
    public static final int SOUND_DOOR_OPEN = 452;
    public static final int SOUND_DOOR_CLOSE = 453;
    public static final int SOUND_TRAPDOOR_OPEN = 454;
    public static final int SOUND_TRAPDOOR_CLOSE = 455;
    public static final int SOUND_FENCE_GATE_OPEN = 456;
    public static final int SOUND_FENCE_GATE_CLOSE = 457;
    public static final int SOUND_INSERT = 458;
    public static final int SOUND_PICKUP = 459;
    public static final int SOUND_INSERT_ENCHANTED = 460;
    public static final int SOUND_PICKUP_ENCHANTED = 461;
    public static final int SOUND_BRUSH = 462;
    public static final int SOUND_BRUSH_COMPLETED = 463;
    public static final int SOUND_SHATTER_DECORATED_POT = 464;
    public static final int SOUND_BREAK_DECORATED_POD = 465;
    public static final int SOUND_SNIFFER_EGG_CRACK = 466;
    public static final int SOUND_SNIFFER_EGG_HATCHED = 467;
    public static final int SOUND_WAXED_SIGN_INTERACT_FAIL = 468;
    public static final int SOUND_RECORD_RELIC = 469;
    public static final int SOUND_BUMP = 470;
    public static final int SOUND_PUMPKIN_CARVE = 471;
    public static final int SOUND_CONVERT_HUSK_TO_ZOMBIE = 472;
    public static final int SOUND_PIG_DEATH = 473;
    public static final int SOUND_HOGLIN_CONVERT_TO_ZOMBIE = 474;
    public static final int SOUND_AMBIENT_UNDERWATER_ENTER = 475;
    public static final int SOUND_AMBIENT_UNDERWATER_EXIT = 476;
    public static final int SOUND_BOTTLE_FILL = 477;
    public static final int SOUND_BOTTLE_EMPTY = 478;
    public static final int SOUND_CRAFTER_CRAFT = 479;
    public static final int SOUND_CRAFTER_FAILED = 480;
    public static final int SOUND_CRAFTER_DISABLE_SLOT = 481;
    public static final int SOUND_DECORATED_POT_INSERT = 482;
    public static final int SOUND_DECORATED_POT_INSERT_FAILED = 483;
    public static final int SOUND_COPPER_BULB_ON = 490;
    public static final int SOUND_COPPER_BULB_OFF = 491;
    public static final int SOUND_AMBIENT_IN_AIR = 492;
    public static final int SOUND_BREEZE_WIND_CHARGE_BURST = 493;
    public static final int SOUND_IMITATE_BREEZE = 494;
    public static final int SOUND_ARMADILLO_BRUSH = 495;
    public static final int SOUND_ARMADILLO_SCUTE_DROP = 496;
    public static final int SOUND_EQUIP_WOLF = 497;
    public static final int SOUND_UNEQUIP_WOLF = 498;
    public static final int SOUND_REFLECT = 499;
    public static final int SOUND_VAULT_OPEN_SHUTTER = 500;
    public static final int SOUND_VAULT_CLOSE_SHUTTER = 501;
    public static final int SOUND_VAULT_EJECT_ITEM = 502;
    public static final int SOUND_VAULT_INSERT_ITEM = 503;
    public static final int SOUND_VAULT_INSERT_ITEM_FAIL = 504;
    public static final int SOUND_VAULT_AMBIENT = 505;
    public static final int SOUND_VAULT_ACTIVATE = 506;
    public static final int SOUND_VAULT_DEACTIVATE = 507;
    public static final int SOUND_HURT_REDUCED = 508;
    public static final int SOUND_WIND_CHARGE_BURST = 509;
    public static final int SOUND_IMITATE_BOGGED = 510;
    public static final int SOUND_WOLF_ARMOR_CRACK = 511;
    public static final int SOUND_WOLF_ARMOR_BREAK = 512;
    public static final int SOUND_WOLF_ARMOR_REPAIR = 513;
    public static final int SOUND_MACE_SMASH_AIR = 514;
    public static final int SOUND_MACE_SMASH_GROUND = 515;
    public static final int SOUND_TRIAL_SPAWNER_CHARGE_ACTIVATE = 516;
    public static final int SOUND_TRIAL_SPAWNER_AMBIENT_OMINOUS = 517;
    public static final int SOUND_OMINOUS_ITEM_SPAWNER_SPAWN_ITEM = 518;
    public static final int SOUND_OMINOUS_BOTTLE_END_USE = 519;
    public static final int SOUND_MACE_HEAVY_SMASH_GROUND = 520;
    public static final int SOUND_OMINOUS_ITEM_SPAWNER_SPAWN_ITEM_BEGIN = 521;
    public static final int SOUND_APPLY_EFFECT_BAD_OMEN = 523;
    public static final int SOUND_APPLY_EFFECT_RAID_OMEN = 524;
    public static final int SOUND_APPLY_EFFECT_TRIAL_OMEN = 525;
    public static final int SOUND_OMINOUS_ITEM_SPAWNER_ABOUT_TO_SPAWN_ITEM = 526;
    public static final int SOUND_RECORD_CREATOR = 527;
    public static final int SOUND_RECORD_CREATOR_MUSIC_BOX = 528;
    public static final int SOUND_RECORD_PRECIPICE = 529;
    public static final int SOUND_VAULT_REJECT_REWARDED_PLAYER = 530;
    public static final int SOUND_IMITATE_DROWNED = 531;
    public static final int SOUND_IMITATE_CREAKING = 532;
    public static final int SOUND_BUNDLE_INSERT_FAIL = 533;
    public static final int SOUND_SPONGE_ABSORB = 534;
    public static final int SOUND_CREAKING_HEART_TRAIL = 536;
    public static final int SOUND_CREAKING_HEART_SPAWN = 537;
    public static final int SOUND_ACTIVATE = 538;
    public static final int SOUND_DEACTIVATE = 539;
    public static final int SOUND_FREEZE = 540;
    public static final int SOUND_UNFREEZE = 541;
    public static final int SOUND_OPEN = 542;
    public static final int SOUND_OPEN_LONG = 543;
    public static final int SOUND_CLOSE = 544;
    public static final int SOUND_CLOSE_LONG = 545;
    public static final int SOUND_IMITATE_PHANTOM = 546;
    public static final int SOUND_IMITATE_ZOGLIN = 547;
    public static final int SOUND_IMITATE_GUARDIAN = 548;
    public static final int SOUND_IMITATE_RAVAGER = 549;
    public static final int SOUND_IMITATE_PILLAGER = 550;
    public static final int SOUND_PLACE_IN_WATER = 551;
    public static final int SOUND_STATE_CHANGE = 552;
    public static final int SOUND_IMITATE_HAPPY_GHAST = 553;
    public static final int SOUND_UNEQUIP_GENERIC = 554;
    public static final int SOUND_RECORD_TEARS = 555;
    public static final int SOUND_THE_END_LIGHT_FLASH = 556;
    public static final int SOUND_LEAD_LEASH = 557;
    public static final int SOUND_LEAD_UNLEASH = 558;
    public static final int SOUND_LEAD_BREAK = 559;
    public static final int SOUND_UNSADDLE = 560;
    public static final int SOUND_EQUIP_COPPER = 561;
    public static final int SOUND_RECORD_LAVA_CHICKEN = 562;
    public static final int SOUND_PLACE_ITEM = 563;
    public static final int SOUND_SINGLE_ITEM_SWAP = 564;
    public static final int SOUND_MULTI_ITEM_SWAP = 565;
    public static final int SOUND_LUNGE_1 = 566;
    public static final int SOUND_LUNGE_2 = 567;
    public static final int SOUND_LUNGE_3 = 568;
    public static final int SOUND_ATTACK_CRITICAL = 569;
    public static final int SOUND_SPEAR_ATTACK_HIT = 570;
    public static final int SOUND_SPEAR_ATTACK_MISS = 571;
    public static final int SOUND_WOODEN_SPEAR_ATTACK_HIT = 572;
    public static final int SOUND_WOODEN_SPEAR_ATTACK_MISS = 573;
    public static final int SOUND_IMITATE_PARCHED = 574;
    public static final int SOUND_IMITATE_CAMEL_HUSK = 575;
    public static final int SOUND_SPEAR_USE = 576;
    public static final int SOUND_WOODEN_SPEAR_USE = 577;
    public static final int SOUND_SADDLE_IN_WATER = 578;
    public static final int SOUND_STONE_SPEAR_ATTACK_HIT = 579;
    public static final int SOUND_IRON_SPEAR_ATTACK_HIT = 580;
    public static final int SOUND_COPPER_SPEAR_ATTACK_HIT = 581;
    public static final int SOUND_GOLDEN_SPEAR_ATTACK_HIT = 582;
    public static final int SOUND_DIAMOND_SPEAR_ATTACK_HIT = 583;
    public static final int SOUND_NETHERITE_SPEAR_ATTACK_HIT = 584;
    public static final int SOUND_STONE_SPEAR_ATTACK_MISS = 585;
    public static final int SOUND_IRON_SPEAR_ATTACK_MISS = 586;
    public static final int SOUND_COPPER_SPEAR_ATTACK_MISS = 587;
    public static final int SOUND_GOLDEN_SPEAR_ATTACK_MISS = 588;
    public static final int SOUND_DIAMOND_SPEAR_ATTACK_MISS = 589;
    public static final int SOUND_NETHERITE_SPEAR_ATTACK_MISS = 590;
    public static final int SOUND_STONE_SPEAR_USE = 591;
    public static final int SOUND_IRON_SPEAR_USE = 592;
    public static final int SOUND_COPPER_SPEAR_USE = 593;
    public static final int SOUND_GOLDEN_SPEAR_USE = 594;
    public static final int SOUND_DIAMOND_SPEAR_USE = 595;
    public static final int SOUND_NETHERITE_SPEAR_USE = 596;
    public static final int SOUND_PAUSE_GROWTH = 597;
    public static final int SOUND_RESET_GROWTH = 598;
    public static final int SOUND_PUSHED_BY_PLAYER = 599;
    public static final int SOUND_BOUNCE = 600;
    public static final int SOUND_SLIME_LANDING = 601;
    public static final int SOUND_ABSORB_BLOCK = 602;
    public static final int SOUND_EJECT_BLOCK = 603;
    public static final int SOUND_GEYSER_ERUPTION_START = 604;
    public static final int SOUND_GEYSER_ERUPTION_ACTIVE = 605;
    public static final int SOUND_RECORD_BOUNCE = 606;
    public static final int SOUND_BUCKET_FILL_LAND_ANIMAL = 607;
    public static final int SOUND_BUCKET_EMPTY_LAND_ANIMAL = 608;
    public static final int SOUND_GEYSER_CONTINUOUS_ERUPTION_START = 609;
    public static final int SOUND_GEYSER_CONTINUOUS_ERUPTION_ACTIVE = 610;

    public int sound;
    public float x;
    public float y;
    public float z;
    public int extraData = -1;
    public String entityIdentifier;
    public boolean isBabyMob;
    public boolean isGlobal;
    public long entityUniqueId = -1;
    public Vector3f fireAtPosition;

    private static final Int2ObjectOpenHashMap<String> SOUND_ID = new Int2ObjectOpenHashMap<>(1024);
    static {
        SOUND_ID.put(0, "item.use.on");
        SOUND_ID.put(1, "hit");
        SOUND_ID.put(2, "step");
        SOUND_ID.put(221, "step.baby");
        SOUND_ID.put(3, "fly");
        SOUND_ID.put(4, "jump");
        SOUND_ID.put(287, "jump.prevent");
        SOUND_ID.put(5, "break");
        SOUND_ID.put(6, "place");
        SOUND_ID.put(7, "heavy.step");
        SOUND_ID.put(8, "gallop");
        SOUND_ID.put(9, "fall");
        SOUND_ID.put(17, "hurt");
        SOUND_ID.put(219, "hurt.baby");
        SOUND_ID.put(18, "hurt.in.water");
        SOUND_ID.put(14, "death");
        SOUND_ID.put(220, "death.baby");
        SOUND_ID.put(15, "death.in.water");
        SOUND_ID.put(16, "death.to.zombie");
        SOUND_ID.put(10, "ambient");
        SOUND_ID.put(11, "ambient.baby");
        SOUND_ID.put(12, "ambient.in.water");
        SOUND_ID.put(492, "ambient.in.air");
        SOUND_ID.put(242, "ambient.tame");
        SOUND_ID.put(288, "ambient.pollinate");
        SOUND_ID.put(13, "breathe");
        SOUND_ID.put(19, "mad");
        SOUND_ID.put(20, "boost");
        SOUND_ID.put(21, "bow");
        SOUND_ID.put(22, "squish.big");
        SOUND_ID.put(23, "squish.small");
        SOUND_ID.put(24, "fall.big");
        SOUND_ID.put(25, "fall.small");
        SOUND_ID.put(26, "splash");
        SOUND_ID.put(27, "fizz");
        SOUND_ID.put(28, "flap");
        SOUND_ID.put(29, "swim");
        SOUND_ID.put(30, "drink");
        SOUND_ID.put(294, "drink.honey");
        SOUND_ID.put(432, "drink.milk");
        SOUND_ID.put(31, "eat");
        SOUND_ID.put(32, "takeoff");
        SOUND_ID.put(33, "shake");
        SOUND_ID.put(34, "plop");
        SOUND_ID.put(35, "land");
        SOUND_ID.put(36, "saddle");
        SOUND_ID.put(37, "armor");
        SOUND_ID.put(38, "mob.armor_stand.place");
        SOUND_ID.put(39, "add.chest");
        SOUND_ID.put(40, "throw");
        SOUND_ID.put(41, "attack");
        SOUND_ID.put(42, "attack.nodamage");
        SOUND_ID.put(43, "attack.strong");
        SOUND_ID.put(44, "warn");
        SOUND_ID.put(45, "shear");
        SOUND_ID.put(46, "milk");
        SOUND_ID.put(47, "thunder");
        SOUND_ID.put(48, "explode");
        SOUND_ID.put(49, "fire");
        SOUND_ID.put(50, "ignite");
        SOUND_ID.put(51, "fuse");
        SOUND_ID.put(52, "stare");
        SOUND_ID.put(53, "spawn");
        SOUND_ID.put(223, "born");
        SOUND_ID.put(54, "shoot");
        SOUND_ID.put(55, "break.block");
        SOUND_ID.put(56, "launch");
        SOUND_ID.put(57, "blast");
        SOUND_ID.put(58, "large.blast");
        SOUND_ID.put(59, "twinkle");
        SOUND_ID.put(60, "remedy");
        SOUND_ID.put(61, "unfect");
        SOUND_ID.put(211, "convert_to_drowned");
        SOUND_ID.put(62, "levelup");
        SOUND_ID.put(63, "bow.hit");
        SOUND_ID.put(64, "bullet.hit");
        SOUND_ID.put(65, "extinguish.fire");
        SOUND_ID.put(66, "item.fizz");
        SOUND_ID.put(67, "chest.open");
        SOUND_ID.put(68, "chest.closed");
        SOUND_ID.put(69, "shulkerbox.open");
        SOUND_ID.put(70, "shulkerbox.closed");
        SOUND_ID.put(71, "enderchest.open");
        SOUND_ID.put(72, "enderchest.closed");
        SOUND_ID.put(73, "power.on");
        SOUND_ID.put(74, "power.off");
        SOUND_ID.put(75, "attach");
        SOUND_ID.put(76, "detach");
        SOUND_ID.put(77, "deny");
        SOUND_ID.put(78, "tripod");
        SOUND_ID.put(79, "pop");
        SOUND_ID.put(80, "drop.slot");
        SOUND_ID.put(81, "note");
        SOUND_ID.put(82, "thorns");
        SOUND_ID.put(83, "piston.in");
        SOUND_ID.put(84, "piston.out");
        SOUND_ID.put(85, "portal");
        SOUND_ID.put(86, "water");
        SOUND_ID.put(87, "lava.pop");
        SOUND_ID.put(88, "lava");
        SOUND_ID.put(229, "beacon.activate");
        SOUND_ID.put(230, "beacon.ambient");
        SOUND_ID.put(231, "beacon.deactivate");
        SOUND_ID.put(232, "beacon.power");
        SOUND_ID.put(233, "conduit.activate");
        SOUND_ID.put(234, "conduit.ambient");
        SOUND_ID.put(235, "conduit.attack");
        SOUND_ID.put(236, "conduit.deactivate");
        SOUND_ID.put(237, "conduit.short");
        SOUND_ID.put(216, "bubble.pop");
        SOUND_ID.put(214, "bubble.up");
        SOUND_ID.put(217, "bubble.upinside");
        SOUND_ID.put(215, "bubble.down");
        SOUND_ID.put(218, "bubble.downinside");
        SOUND_ID.put(89, "burp");
        SOUND_ID.put(90, "bucket.fill.water");
        SOUND_ID.put(92, "bucket.empty.water");
        SOUND_ID.put(91, "bucket.fill.lava");
        SOUND_ID.put(93, "bucket.empty.lava");
        SOUND_ID.put(212, "bucket.fill.fish");
        SOUND_ID.put(213, "bucket.empty.fish");
        SOUND_ID.put(94, "armor.equip_chain");
        SOUND_ID.put(95, "armor.equip_diamond");
        SOUND_ID.put(100, "armor.equip_elytra");
        SOUND_ID.put(96, "armor.equip_generic");
        SOUND_ID.put(97, "armor.equip_gold");
        SOUND_ID.put(98, "armor.equip_iron");
        SOUND_ID.put(99, "armor.equip_leather");
        SOUND_ID.put(317, "armor.equip_netherite");
        SOUND_ID.put(101, "record.13");
        SOUND_ID.put(102, "record.cat");
        SOUND_ID.put(103, "record.blocks");
        SOUND_ID.put(104, "record.chirp");
        SOUND_ID.put(527, "record.creator");
        SOUND_ID.put(528, "record.creator_music_box");
        SOUND_ID.put(105, "record.far");
        SOUND_ID.put(106, "record.mall");
        SOUND_ID.put(107, "record.mellohi");
        SOUND_ID.put(108, "record.stal");
        SOUND_ID.put(109, "record.strad");
        SOUND_ID.put(110, "record.ward");
        SOUND_ID.put(111, "record.11");
        SOUND_ID.put(112, "record.wait");
        SOUND_ID.put(113, "record.null");
        SOUND_ID.put(314, "record.pigstep");
        SOUND_ID.put(529, "record.precipice");
        SOUND_ID.put(469, "record.relic");
        SOUND_ID.put(371, "record.otherside");
        SOUND_ID.put(439, "record.5");
        SOUND_ID.put(555, "record.tears");
        SOUND_ID.put(562, "record.lava_chicken");
        SOUND_ID.put(114, "flop");
        SOUND_ID.put(115, "elderguardian.curse");
        SOUND_ID.put(118, "teleport");
        SOUND_ID.put(119, "shulker.open");
        SOUND_ID.put(120, "shulker.close");
        SOUND_ID.put(116, "mob.warning");
        SOUND_ID.put(117, "mob.warning.baby");
        SOUND_ID.put(121, "haggle");
        SOUND_ID.put(122, "haggle.yes");
        SOUND_ID.put(123, "haggle.no");
        SOUND_ID.put(124, "haggle.idle");
        SOUND_ID.put(430, "disappeared");
        SOUND_ID.put(431, "reappeared");
        SOUND_ID.put(125, "chorusgrow");
        SOUND_ID.put(126, "chorusdeath");
        SOUND_ID.put(127, "glass");
        SOUND_ID.put(128, "potion.brewed");
        SOUND_ID.put(129, "cast.spell");
        SOUND_ID.put(130, "prepare.attack");
        SOUND_ID.put(131, "prepare.summon");
        SOUND_ID.put(132, "prepare.wololo");
        SOUND_ID.put(133, "fang");
        SOUND_ID.put(134, "charge");
        SOUND_ID.put(135, "camera.take_picture");
        SOUND_ID.put(137, "leashknot.break");
        SOUND_ID.put(136, "leashknot.place");
        SOUND_ID.put(138, "growl");
        SOUND_ID.put(139, "whine");
        SOUND_ID.put(140, "pant");
        SOUND_ID.put(141, "purr");
        SOUND_ID.put(142, "purreow");
        SOUND_ID.put(143, "death.min.volume");
        SOUND_ID.put(144, "death.mid.volume");
        SOUND_ID.put(145, "imitate.blaze");
        SOUND_ID.put(146, "imitate.cave_spider");
        SOUND_ID.put(147, "imitate.creeper");
        SOUND_ID.put(148, "imitate.elder_guardian");
        SOUND_ID.put(149, "imitate.ender_dragon");
        SOUND_ID.put(150, "imitate.enderman");
        SOUND_ID.put(151, "imitate.endermite");
        SOUND_ID.put(152, "imitate.evocation_illager");
        SOUND_ID.put(153, "imitate.ghast");
        SOUND_ID.put(154, "imitate.husk");
        SOUND_ID.put(156, "imitate.magma_cube");
        SOUND_ID.put(157, "imitate.polar_bear");
        SOUND_ID.put(158, "imitate.shulker");
        SOUND_ID.put(159, "imitate.silverfish");
        SOUND_ID.put(160, "imitate.skeleton");
        SOUND_ID.put(161, "imitate.slime");
        SOUND_ID.put(162, "imitate.spider");
        SOUND_ID.put(163, "imitate.stray");
        SOUND_ID.put(164, "imitate.vex");
        SOUND_ID.put(165, "imitate.vindication_illager");
        SOUND_ID.put(166, "imitate.witch");
        SOUND_ID.put(167, "imitate.wither");
        SOUND_ID.put(168, "imitate.wither_skeleton");
        SOUND_ID.put(169, "imitate.wolf");
        SOUND_ID.put(170, "imitate.zombie");
        SOUND_ID.put(171, "imitate.zombie_pigman");
        SOUND_ID.put(172, "imitate.zombie_villager");
        SOUND_ID.put(173, "block.end_portal_frame.fill");
        SOUND_ID.put(174, "block.end_portal.spawn");
        SOUND_ID.put(175, "random.anvil_use");
        SOUND_ID.put(176, "bottle.dragonbreath");
        SOUND_ID.put(190, "balloonpop");
        SOUND_ID.put(210, "sparkler.active");
        SOUND_ID.put(178, "item.trident.hit");
        SOUND_ID.put(185, "item.trident.hit_ground");
        SOUND_ID.put(179, "item.trident.return");
        SOUND_ID.put(180, "item.trident.riptide_1");
        SOUND_ID.put(181, "item.trident.riptide_2");
        SOUND_ID.put(182, "item.trident.riptide_3");
        SOUND_ID.put(183, "item.trident.throw");
        SOUND_ID.put(184, "item.trident.thunder");
        SOUND_ID.put(187, "block.fletching_table.use");
        SOUND_ID.put(188, "elemconstruct.open");
        SOUND_ID.put(189, "icebomb.hit");
        SOUND_ID.put(191, "lt.reaction.icebomb");
        SOUND_ID.put(192, "lt.reaction.bleach");
        SOUND_ID.put(193, "lt.reaction.epaste");
        SOUND_ID.put(194, "lt.reaction.epaste2");
        SOUND_ID.put(199, "lt.reaction.fertilizer");
        SOUND_ID.put(200, "lt.reaction.fireball");
        SOUND_ID.put(201, "lt.reaction.mgsalt");
        SOUND_ID.put(202, "lt.reaction.miscfire");
        SOUND_ID.put(203, "lt.reaction.fire");
        SOUND_ID.put(204, "lt.reaction.miscexplosion");
        SOUND_ID.put(205, "lt.reaction.miscmystical");
        SOUND_ID.put(206, "lt.reaction.miscmystical2");
        SOUND_ID.put(207, "lt.reaction.product");
        SOUND_ID.put(208, "sparkler.use");
        SOUND_ID.put(209, "glowstick.use");
        SOUND_ID.put(224, "block.turtle_egg.break");
        SOUND_ID.put(225, "block.turtle_egg.crack");
        SOUND_ID.put(226, "block.turtle_egg.hatch");
        SOUND_ID.put(228, "block.turtle_egg.attack");
        SOUND_ID.put(466, "block.sniffer_egg.crack");
        SOUND_ID.put(467, "block.sniffer_egg.hatch");
        SOUND_ID.put(433, "block.frog_spawn.hatch");
        SOUND_ID.put(435, "block.frog_spawn.break");
        SOUND_ID.put(238, "swoop");
        SOUND_ID.put(240, "presneeze");
        SOUND_ID.put(241, "sneeze");
        SOUND_ID.put(243, "scared");
        SOUND_ID.put(252, "ambient.aggressive");
        SOUND_ID.put(253, "ambient.worried");
        SOUND_ID.put(254, "cant_breed");
        SOUND_ID.put(244, "block.scaffolding.climb");
        SOUND_ID.put(239, "block.bamboo_sapling.place");
        SOUND_ID.put(245, "crossbow.loading.start");
        SOUND_ID.put(246, "crossbow.loading.middle");
        SOUND_ID.put(247, "crossbow.loading.end");
        SOUND_ID.put(248, "crossbow.shoot");
        SOUND_ID.put(249, "crossbow.quick_charge.start");
        SOUND_ID.put(250, "crossbow.quick_charge.middle");
        SOUND_ID.put(251, "crossbow.quick_charge.end");
        SOUND_ID.put(255, "item.shield.block");
        SOUND_ID.put(177, "portal.travel");
        SOUND_ID.put(256, "item.book.put");
        SOUND_ID.put(257, "block.grindstone.use");
        SOUND_ID.put(258, "block.bell.hit");
        SOUND_ID.put(259, "block.campfire.crackle");
        SOUND_ID.put(262, "block.sweet_berry_bush.hurt");
        SOUND_ID.put(263, "block.sweet_berry_bush.pick");
        SOUND_ID.put(265, "block.stonecutter.use");
        SOUND_ID.put(264, "block.cartography_table.use");
        SOUND_ID.put(266, "block.composter.empty");
        SOUND_ID.put(267, "block.composter.fill");
        SOUND_ID.put(268, "block.composter.fill_success");
        SOUND_ID.put(269, "block.composter.ready");
        SOUND_ID.put(260, "roar");
        SOUND_ID.put(261, "stun");
        SOUND_ID.put(270, "block.barrel.open");
        SOUND_ID.put(271, "block.barrel.close");
        SOUND_ID.put(272, "raid.horn");
        SOUND_ID.put(276, "ui.stonecutter.take_result");
        SOUND_ID.put(275, "ui.cartography_table.take_result");
        SOUND_ID.put(277, "ui.loom.take_result");
        SOUND_ID.put(278, "block.smoker.smoke");
        SOUND_ID.put(279, "block.blastfurnace.fire_crackle");
        SOUND_ID.put(280, "block.smithing_table.use");
        SOUND_ID.put(273, "block.loom.use");
        SOUND_ID.put(274, "ambient.in.raid");
        SOUND_ID.put(281, "screech");
        SOUND_ID.put(282, "sleep");
        SOUND_ID.put(283, "block.furnace.lit");
        SOUND_ID.put(284, "convert_mooshroom");
        SOUND_ID.put(285, "milk_suspiciously");
        SOUND_ID.put(286, "celebrate");
        SOUND_ID.put(290, "block.beehive.enter");
        SOUND_ID.put(291, "block.beehive.exit");
        SOUND_ID.put(293, "block.beehive.shear");
        SOUND_ID.put(292, "block.beehive.work");
        SOUND_ID.put(289, "block.beehive.drip");
        SOUND_ID.put(295, "ambient.cave");
        SOUND_ID.put(302, "angry");
        SOUND_ID.put(296, "retreat");
        SOUND_ID.put(297, "converted_to_zombified");
        SOUND_ID.put(299, "step_lava");
        SOUND_ID.put(300, "tempt");
        SOUND_ID.put(301, "panic");
        SOUND_ID.put(298, "admire");
        SOUND_ID.put(312, "particle.soul_escape.quiet");
        SOUND_ID.put(313, "particle.soul_escape.loud");
        SOUND_ID.put(308, "respawn_anchor.charge");
        SOUND_ID.put(309, "respawn_anchor.deplete");
        SOUND_ID.put(310, "respawn_anchor.set_spawn");
        SOUND_ID.put(311, "respawn_anchor.ambient");
        SOUND_ID.put(307, "ambient.crimson_forest.mood");
        SOUND_ID.put(303, "ambient.warped_forest.mood");
        SOUND_ID.put(304, "ambient.soulsand_valley.mood");
        SOUND_ID.put(305, "ambient.nether_wastes.mood");
        SOUND_ID.put(327, "ambient.crimson_forest.additions");
        SOUND_ID.put(323, "ambient.warped_forest.additions");
        SOUND_ID.put(324, "ambient.soulsand_valley.additions");
        SOUND_ID.put(325, "ambient.nether_wastes.additions");
        SOUND_ID.put(326, "ambient.basalt_deltas.additions");
        SOUND_ID.put(322, "ambient.crimson_forest.loop");
        SOUND_ID.put(318, "ambient.warped_forest.loop");
        SOUND_ID.put(319, "ambient.soulsand_valley.loop");
        SOUND_ID.put(320, "ambient.nether_wastes.loop");
        SOUND_ID.put(321, "ambient.basalt_deltas.loop");
        SOUND_ID.put(315, "lodestone_compass.link_compass_to_lodestone");
        SOUND_ID.put(306, "ambient.basalt_deltas.mood");
        SOUND_ID.put(328, "power.on.sculk_sensor");
        SOUND_ID.put(329, "power.off.sculk_sensor");
        SOUND_ID.put(316, "smithing_table.use");
        SOUND_ID.put(186, "default");
        SOUND_ID.put(227, "lay_egg");
        SOUND_ID.put(434, "lay_spawn");
        SOUND_ID.put(330, "bucket.fill.powder_snow");
        SOUND_ID.put(331, "bucket.empty.powder_snow");
        SOUND_ID.put(332, "cauldron_drip.water.pointed_dripstone");
        SOUND_ID.put(333, "cauldron_drip.lava.pointed_dripstone");
        SOUND_ID.put(337, "tilt_down.big_dripleaf");
        SOUND_ID.put(338, "tilt_up.big_dripleaf");
        SOUND_ID.put(334, "drip.water.pointed_dripstone");
        SOUND_ID.put(336, "pick_berries.cave_vines");
        SOUND_ID.put(335, "drip.lava.pointed_dripstone");
        SOUND_ID.put(339, "copper.wax.on");
        SOUND_ID.put(340, "copper.wax.off");
        SOUND_ID.put(341, "scrape");
        SOUND_ID.put(345, "item.spyglass.use");
        SOUND_ID.put(346, "item.spyglass.stop_using");
        SOUND_ID.put(347, "chime.amethyst_block");
        SOUND_ID.put(342, "mob.player.hurt_drown");
        SOUND_ID.put(343, "mob.player.hurt_on_fire");
        SOUND_ID.put(344, "mob.player.hurt_freeze");
        SOUND_ID.put(348, "ambient.screamer");
        SOUND_ID.put(349, "hurt.screamer");
        SOUND_ID.put(350, "death.screamer");
        SOUND_ID.put(351, "milk.screamer");
        SOUND_ID.put(352, "jump_to_block");
        SOUND_ID.put(353, "pre_ram");
        SOUND_ID.put(354, "pre_ram.screamer");
        SOUND_ID.put(355, "ram_impact");
        SOUND_ID.put(356, "ram_impact.screamer");
        SOUND_ID.put(357, "squid.ink_squirt");
        SOUND_ID.put(358, "glow_squid.ink_squirt");
        SOUND_ID.put(359, "convert_to_stray");
        SOUND_ID.put(360, "cake.add_candle");
        SOUND_ID.put(361, "extinguish.candle");
        SOUND_ID.put(362, "ambient.candle");
        SOUND_ID.put(363, "block.click");
        SOUND_ID.put(364, "block.click.fail");
        SOUND_ID.put(365, "block.sculk_catalyst.bloom");
        SOUND_ID.put(366, "block.sculk_shrieker.shriek");
        SOUND_ID.put(367, "nearby_close");
        SOUND_ID.put(368, "nearby_closer");
        SOUND_ID.put(369, "nearby_closest");
        SOUND_ID.put(370, "agitated");
        SOUND_ID.put(375, "listening");
        SOUND_ID.put(376, "heartbeat");
        SOUND_ID.put(372, "tongue");
        SOUND_ID.put(428, "item_given");
        SOUND_ID.put(429, "item_taken");
        SOUND_ID.put(438, "item_thrown");
        SOUND_ID.put(373, "irongolem.crack");
        SOUND_ID.put(374, "irongolem.repair");
        SOUND_ID.put(377, "horn_break");
        SOUND_ID.put(383, "horn_call0");
        SOUND_ID.put(384, "horn_call1");
        SOUND_ID.put(385, "horn_call2");
        SOUND_ID.put(386, "horn_call3");
        SOUND_ID.put(387, "horn_call4");
        SOUND_ID.put(388, "horn_call5");
        SOUND_ID.put(389, "horn_call6");
        SOUND_ID.put(390, "horn_call7");
        SOUND_ID.put(426, "imitate.warden");
        SOUND_ID.put(427, "listening_angry");
        SOUND_ID.put(436, "sonic_boom");
        SOUND_ID.put(437, "sonic_charge");
        SOUND_ID.put(440, "convert_to_frog");
        SOUND_ID.put(379, "block.sculk.spread");
        SOUND_ID.put(380, "charge.sculk");
        SOUND_ID.put(381, "block.sculk_sensor.place");
        SOUND_ID.put(382, "block.sculk_shrieker.place");
        SOUND_ID.put(442, "block.enchanting_table.use");
        SOUND_ID.put(445, "bundle.drop_contents");
        SOUND_ID.put(446, "bundle.insert");
        SOUND_ID.put(533, "bundle.insert_fail");
        SOUND_ID.put(447, "bundle.remove_one");
        SOUND_ID.put(443, "step_sand");
        SOUND_ID.put(444, "dash_ready");
        SOUND_ID.put(448, "pressure_plate.click_off");
        SOUND_ID.put(449, "pressure_plate.click_on");
        SOUND_ID.put(450, "button.click_off");
        SOUND_ID.put(451, "button.click_on");
        SOUND_ID.put(452, "door.open");
        SOUND_ID.put(453, "door.close");
        SOUND_ID.put(454, "trapdoor.open");
        SOUND_ID.put(455, "trapdoor.close");
        SOUND_ID.put(456, "fence_gate.open");
        SOUND_ID.put(457, "fence_gate.close");
        SOUND_ID.put(458, "insert");
        SOUND_ID.put(459, "pickup");
        SOUND_ID.put(460, "insert_enchanted");
        SOUND_ID.put(461, "pickup_enchanted");
        SOUND_ID.put(464, "shatter_pot");
        SOUND_ID.put(465, "break_pot");
        SOUND_ID.put(462, "brush");
        SOUND_ID.put(463, "brush_completed");
        SOUND_ID.put(468, "block.sign.waxed_interact_fail");
        SOUND_ID.put(470, "note.bass");
        SOUND_ID.put(471, "pumpkin.carve");
        SOUND_ID.put(472, "mob.husk.convert_to_zombie");
        SOUND_ID.put(473, "mob.pig.death");
        SOUND_ID.put(474, "mob.hoglin.converted_to_zombified");
        SOUND_ID.put(475, "ambient.underwater.enter");
        SOUND_ID.put(476, "ambient.underwater.exit");
        SOUND_ID.put(477, "bottle.fill");
        SOUND_ID.put(478, "bottle.empty");
        SOUND_ID.put(481, "block.decorated_pot.insert");
        SOUND_ID.put(482, "block.decorated_pot.insert_fail");
        SOUND_ID.put(479, "crafter.craft");
        SOUND_ID.put(480, "crafter.fail");
        SOUND_ID.put(483, "crafter.disable_slot");
        SOUND_ID.put(490, "block.copper_bulb.turn_on");
        SOUND_ID.put(491, "block.copper_bulb.turn_off");
        SOUND_ID.put(493, "breeze_wind_charge.burst");
        SOUND_ID.put(494, "imitate.breeze");
        SOUND_ID.put(484, "trial_spawner.open_shutter");
        SOUND_ID.put(486, "trial_spawner.detect_player");
        SOUND_ID.put(488, "trial_spawner.close_shutter");
        SOUND_ID.put(487, "trial_spawner.spawn_mob");
        SOUND_ID.put(485, "trial_spawner.eject_item");
        SOUND_ID.put(489, "trial_spawner.ambient");
        SOUND_ID.put(495, "mob.armadillo.brush");
        SOUND_ID.put(496, "mob.armadillo.scute_drop");
        SOUND_ID.put(497, "armor.equip_wolf");
        SOUND_ID.put(498, "armor.unequip_wolf");
        SOUND_ID.put(499, "reflect");
        SOUND_ID.put(500, "vault.open_shutter");
        SOUND_ID.put(501, "vault.close_shutter");
        SOUND_ID.put(502, "vault.eject_item");
        SOUND_ID.put(503, "vault.insert_item");
        SOUND_ID.put(504, "vault.insert_item_fail");
        SOUND_ID.put(505, "vault.ambient");
        SOUND_ID.put(506, "vault.activate");
        SOUND_ID.put(507, "vault.deactivate");
        SOUND_ID.put(508, "hurt.reduced");
        SOUND_ID.put(509, "wind_charge.burst");
        SOUND_ID.put(512, "armor.break_wolf");
        SOUND_ID.put(511, "armor.crack_wolf");
        SOUND_ID.put(513, "armor.repair_wolf");
        SOUND_ID.put(514, "mace.smash_air");
        SOUND_ID.put(515, "mace.smash_ground");
        SOUND_ID.put(520, "mace.heavy_smash_ground");
        SOUND_ID.put(516, "trial_spawner.charge_activate");
        SOUND_ID.put(517, "trial_spawner.ambient_ominous");
        SOUND_ID.put(523, "apply_effect.bad_omen");
        SOUND_ID.put(524, "apply_effect.raid_omen");
        SOUND_ID.put(525, "apply_effect.trial_omen");
        SOUND_ID.put(518, "ominous_item_spawner.spawn_item");
        SOUND_ID.put(519, "ominous_bottle.end_use");
        SOUND_ID.put(521, "ominous_item_spawner.spawn_item_begin");
        SOUND_ID.put(526, "ominous_item_spawner.about_to_spawn_item");
        SOUND_ID.put(510, "imitate.bogged");
        SOUND_ID.put(530, "vault.reject_rewarded_player");
        SOUND_ID.put(531, "imitate.drowned");
        SOUND_ID.put(534, "sponge.absorb");
        SOUND_ID.put(532, "imitate.creaking");
        SOUND_ID.put(536, "block.creaking_heart.trail");
        SOUND_ID.put(537, "creaking_heart_spawn");
        SOUND_ID.put(538, "activate");
        SOUND_ID.put(539, "deactivate");
        SOUND_ID.put(540, "freeze");
        SOUND_ID.put(541, "unfreeze");
        SOUND_ID.put(542, "open");
        SOUND_ID.put(543, "open_long");
        SOUND_ID.put(544, "close");
        SOUND_ID.put(545, "close_long");
        SOUND_ID.put(546, "imitate.phantom");
        SOUND_ID.put(547, "imitate.zoglin");
        SOUND_ID.put(548, "imitate.guardian");
        SOUND_ID.put(549, "imitate.ravager");
        SOUND_ID.put(550, "imitate.pillager");
        SOUND_ID.put(551, "place_in_water");
        SOUND_ID.put(552, "state_change");
        SOUND_ID.put(553, "imitate.happy_ghast");
        SOUND_ID.put(554, "armor.unequip_generic");
        SOUND_ID.put(556, "ambient.weather.the_end_light_flash");
        SOUND_ID.put(557, "lead.leash");
        SOUND_ID.put(558, "lead.unleash");
        SOUND_ID.put(559, "lead.break");
        SOUND_ID.put(560, "unsaddle");
        SOUND_ID.put(561, "armor.equip_copper");
        SOUND_ID.put(563, "place_item");
        SOUND_ID.put(564, "single_swap");
        SOUND_ID.put(565, "multi_swap");
        SOUND_ID.put(566, "item.enchant.lunge1");
        SOUND_ID.put(567, "item.enchant.lunge2");
        SOUND_ID.put(568, "item.enchant.lunge3");
        SOUND_ID.put(569, "attack.critical");
        SOUND_ID.put(570, "item.spear.attack_hit");
        SOUND_ID.put(571, "item.spear.attack_miss");
        SOUND_ID.put(572, "item.wooden_spear.attack_hit");
        SOUND_ID.put(573, "item.wooden_spear.attack_miss");
        SOUND_ID.put(574, "imitate.parched");
        SOUND_ID.put(575, "imitate.camel_husk");
        SOUND_ID.put(576, "item.spear.use");
        SOUND_ID.put(577, "item.wooden_spear.use");
        SOUND_ID.put(578, "saddle_in_water");
        SOUND_ID.put(579, "item.stone_spear.attack_hit");
        SOUND_ID.put(580, "item.iron_spear.attack_hit");
        SOUND_ID.put(581, "item.copper_spear.attack_hit");
        SOUND_ID.put(582, "item.golden_spear.attack_hit");
        SOUND_ID.put(583, "item.diamond_spear.attack_hit");
        SOUND_ID.put(584, "item.netherite_spear.attack_hit");
        SOUND_ID.put(585, "item.stone_spear.attack_miss");
        SOUND_ID.put(586, "item.iron_spear.attack_miss");
        SOUND_ID.put(587, "item.copper_spear.attack_miss");
        SOUND_ID.put(588, "item.golden_spear.attack_miss");
        SOUND_ID.put(589, "item.diamond_spear.attack_miss");
        SOUND_ID.put(590, "item.netherite_spear.attack_miss");
        SOUND_ID.put(591, "item.stone_spear.use");
        SOUND_ID.put(592, "item.iron_spear.use");
        SOUND_ID.put(593, "item.copper_spear.use");
        SOUND_ID.put(594, "item.golden_spear.use");
        SOUND_ID.put(595, "item.diamond_spear.use");
        SOUND_ID.put(596, "item.netherite_spear.use");
        SOUND_ID.put(597, "pause_growth");
        SOUND_ID.put(598, "reset_growth");
        SOUND_ID.put(599, "pushed_by_player");
        SOUND_ID.put(600, "bounce");
        SOUND_ID.put(601, "slime_landing");
        SOUND_ID.put(602, "absorb_block");
        SOUND_ID.put(603, "eject_block");
        SOUND_ID.put(604, "geyser_eruption_start");
        SOUND_ID.put(605, "geyser_eruption_active");
        SOUND_ID.put(606, "record.bounce");
        SOUND_ID.put(607, "bucket.fill.land_animal");
        SOUND_ID.put(608, "bucket.empty.land_animal");
        SOUND_ID.put(609, "geyser_continuous_eruption_start");
        SOUND_ID.put(610, "geyser_continuous_eruption_active");
        SOUND_ID.put(611, "undefined");
        SOUND_ID.trim();
    }

    @Override
    public void decode() {
        if (Nukkit.DEBUG > 1) {
            Server.getInstance().getLogger().debug("decode(): Ignored incoming LevelSoundEventPacket");
        }
    }

    @Override
    public void encode() {
        this.reset();
        this.putString(SOUND_ID.getOrDefault(this.sound, "undefined"));
        this.putVector3f(this.x, this.y, this.z);
        this.putVarInt(this.extraData);
        this.putString(this.entityIdentifier);
        this.putBoolean(this.isBabyMob);
        this.putBoolean(this.isGlobal);
        this.putLLong(this.entityUniqueId);
        this.putOptionalNull(this.fireAtPosition, BinaryStream::putVector3f);
    }

    @Override
    public byte pid() {
        return NETWORK_ID;
    }
}
