apiVersion: v1
kind: Service
metadata:
  name: {{ include "nukkit.fullname" . }}
  labels:
    {{- include "nukkit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: udp
      protocol: UDP
      name: udp
{{- if eq .Values.service.port "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    {{- include "nukkit.selectorLabels" . | nindent 4 }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
