package cn.nukkit.level.biome;

import cn.nukkit.utils.Identifier;
import lombok.experimental.UtilityClass;

@UtilityClass
public class BiomeIds {
    //sorted by legacy ID
    public static final Identifier OCEAN = Identifier.fromString("ocean");
    public static final Identifier PLAINS = Identifier.fromString("plains");
    public static final Identifier DESERT = Identifier.fromString("desert");
    public static final Identifier EXTREME_HILLS = Identifier.fromString("extreme_hills");
    public static final Identifier FOREST = Identifier.fromString("forest");
    public static final Identifier TAIGA = Identifier.fromString("taiga");
    public static final Identifier SWAMPLAND = Identifier.fromString("swampland");
    public static final Identifier RIVER = Identifier.fromString("river");
    public static final Identifier HELL = Identifier.fromString("hell");
    public static final Identifier THE_END = Identifier.fromString("the_end");
    public static final Identifier LEGACY_FROZEN_OCEAN = Identifier.fromString("legacy_frozen_ocean");
    public static final Identifier FROZEN_RIVER = Identifier.fromString("frozen_river");
    public static final Identifier ICE_PLAINS = Identifier.fromString("ice_plains");
    public static final Identifier ICE_MOUNTAINS = Identifier.fromString("ice_mountains");
    public static final Identifier MUSHROOM_ISLAND = Identifier.fromString("mushroom_island");
    public static final Identifier MUSHROOM_ISLAND_SHORE = Identifier.fromString("mushroom_island_shore");
    public static final Identifier BEACH = Identifier.fromString("beach");
    public static final Identifier DESERT_HILLS = Identifier.fromString("desert_hills");
    public static final Identifier FOREST_HILLS = Identifier.fromString("forest_hills");
    public static final Identifier TAIGA_HILLS = Identifier.fromString("taiga_hills");
    public static final Identifier EXTREME_HILLS_EDGE = Identifier.fromString("extreme_hills_edge");
    public static final Identifier JUNGLE = Identifier.fromString("jungle");
    public static final Identifier JUNGLE_HILLS = Identifier.fromString("jungle_hills");
    public static final Identifier JUNGLE_EDGE = Identifier.fromString("jungle_edge");
    public static final Identifier DEEP_OCEAN = Identifier.fromString("deep_ocean");
    public static final Identifier STONE_BEACH = Identifier.fromString("stone_beach");
    public static final Identifier COLD_BEACH = Identifier.fromString("cold_beach");
    public static final Identifier BIRCH_FOREST = Identifier.fromString("birch_forest");
    public static final Identifier BIRCH_FOREST_HILLS = Identifier.fromString("birch_forest_hills");
    public static final Identifier ROOFED_FOREST = Identifier.fromString("roofed_forest");
    public static final Identifier COLD_TAIGA = Identifier.fromString("cold_taiga");
    public static final Identifier COLD_TAIGA_HILLS = Identifier.fromString("cold_taiga_hills");
    public static final Identifier MEGA_TAIGA = Identifier.fromString("mega_taiga");
    public static final Identifier MEGA_TAIGA_HILLS = Identifier.fromString("mega_taiga_hills");
    public static final Identifier EXTREME_HILLS_PLUS_TREES = Identifier.fromString("extreme_hills_plus_trees");
    public static final Identifier SAVANNA = Identifier.fromString("savanna");
    public static final Identifier SAVANNA_PLATEAU = Identifier.fromString("savanna_plateau");
    public static final Identifier MESA = Identifier.fromString("mesa");
    public static final Identifier MESA_PLATEAU_STONE = Identifier.fromString("mesa_plateau_stone");
    public static final Identifier MESA_PLATEAU = Identifier.fromString("mesa_plateau");
    public static final Identifier WARM_OCEAN = Identifier.fromString("warm_ocean");
    public static final Identifier DEEP_WARM_OCEAN = Identifier.fromString("deep_warm_ocean");
    public static final Identifier LUKEWARM_OCEAN = Identifier.fromString("lukewarm_ocean");
    public static final Identifier DEEP_LUKEWARM_OCEAN = Identifier.fromString("deep_lukewarm_ocean");
    public static final Identifier COLD_OCEAN = Identifier.fromString("cold_ocean");
    public static final Identifier DEEP_COLD_OCEAN = Identifier.fromString("deep_cold_ocean");
    public static final Identifier FROZEN_OCEAN = Identifier.fromString("frozen_ocean");
    public static final Identifier DEEP_FROZEN_OCEAN = Identifier.fromString("deep_frozen_ocean");
    public static final Identifier BAMBOO_JUNGLE = Identifier.fromString("bamboo_jungle");
    public static final Identifier BAMBOO_JUNGLE_HILLS = Identifier.fromString("bamboo_jungle_hills");
    public static final Identifier SUNFLOWER_PLAINS = Identifier.fromString("sunflower_plains");
    public static final Identifier DESERT_MUTATED = Identifier.fromString("desert_mutated");
    public static final Identifier EXTREME_HILLS_MUTATED = Identifier.fromString("extreme_hills_mutated");
    public static final Identifier FLOWER_FOREST = Identifier.fromString("flower_forest");
    public static final Identifier TAIGA_MUTATED = Identifier.fromString("taiga_mutated");
    public static final Identifier SWAMPLAND_MUTATED = Identifier.fromString("swampland_mutated");
    public static final Identifier ICE_PLAINS_SPIKES = Identifier.fromString("ice_plains_spikes");
    public static final Identifier JUNGLE_MUTATED = Identifier.fromString("jungle_mutated");
    public static final Identifier JUNGLE_EDGE_MUTATED = Identifier.fromString("jungle_edge_mutated");
    public static final Identifier BIRCH_FOREST_MUTATED = Identifier.fromString("birch_forest_mutated");
    public static final Identifier BIRCH_FOREST_HILLS_MUTATED = Identifier.fromString("birch_forest_hills_mutated");
    public static final Identifier ROOFED_FOREST_MUTATED = Identifier.fromString("roofed_forest_mutated");
    public static final Identifier COLD_TAIGA_MUTATED = Identifier.fromString("cold_taiga_mutated");
    public static final Identifier REDWOOD_TAIGA_MUTATED = Identifier.fromString("redwood_taiga_mutated");
    public static final Identifier REDWOOD_TAIGA_HILLS_MUTATED = Identifier.fromString("redwood_taiga_hills_mutated");
    public static final Identifier EXTREME_HILLS_PLUS_TREES_MUTATED = Identifier.fromString("extreme_hills_plus_trees_mutated");
    public static final Identifier SAVANNA_MUTATED = Identifier.fromString("savanna_mutated");
    public static final Identifier SAVANNA_PLATEAU_MUTATED = Identifier.fromString("savanna_plateau_mutated");
    public static final Identifier MESA_BRYCE = Identifier.fromString("mesa_bryce");
    public static final Identifier MESA_PLATEAU_STONE_MUTATED = Identifier.fromString("mesa_plateau_stone_mutated");
    public static final Identifier MESA_PLATEAU_MUTATED = Identifier.fromString("mesa_plateau_mutated");
}
