name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: SetupJDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: "publishNukkitPublicationToOpencollabRepository"
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true -Dorg.gradle.welcome=never"
          DEPLOY_USERNAME: ${{ vars.OPENCOLLAB_USERNAME }}
          DEPLOY_PASSWORD: ${{ secrets.OPENCOLLAB_PASSWORD }}
